# abook
# Autogenerated from man page /usr/share/man/man1/abook.1.gz
# using Deroffing man parser
complete -c abook -s h -l help --description 'Show usage.'
complete -c abook -s C -l config --description 'Use an alternative configuration file (default is $HOME/.'
complete -c abook -l datafile --description 'Use an alternative addressbook file (default is $HOME/.'
complete -c abook -l mutt-query --description 'Make a query for mutt (search the addressbook for <string>).'
complete -c abook -l convert -l informat -l infile -l outformat -l outfile --description 'Converts <inputfile> in <inputformat> to <outpu… [See Man Page]'
complete -c abook -l add-email --description 'Read an e-mail message from stdin and add the s… [See Man Page]'
complete -c abook -l add-email-quiet --description 'Same as --add-email but doesn\'t confirm adding.'
complete -c abook -l formats --description 'List available formats.'

