# anki
# Autogenerated from man page /usr/share/man/man1/anki.1.gz
# using Deroffing man parser
complete -c anki -s b --description 'Use ~/. anki instead of ~/Anki as Anki\'s base folder.'
complete -c anki -s p --description 'Load a specific profile.'
complete -c anki -s l --description 'Start the program in a specific language (de=Ge… [See Man Page]'

