# ar
# Autogenerated from man page /usr/share/man/man1/ar.1p.gz
# using Deroffing man parser
complete -c ar -s a --description 'Position new files in the archive after the fil… [See Man Page]'
complete -c ar -s b --description 'Position new files in the archive before the fi… [See Man Page]'
complete -c ar -s c --description 'Suppress the diagnostic message that is written… [See Man Page]'
complete -c ar -s C --description 'Prevent extracted files from replacing like-nam… [See Man Page]'
complete -c ar -s d --description 'Delete one or more files from archive.'
complete -c ar -s i --description 'Position new files in the archive before the fi… [See Man Page]'
complete -c ar -s m --description 'Move the named files in the archive.'
complete -c ar -s p --description 'Write the contents of the files in the archive … [See Man Page]'
complete -c ar -s q --description 'Append the named files to the end of the archive.'
complete -c ar -s r --description 'Replace or add files to archive.'
complete -c ar -s s --description 'Force the regeneration of the archive symbol ta… [See Man Page]'
complete -c ar -s t --description 'Write a table of contents of archive to the standard output.'
complete -c ar -s T --description 'Allow filename truncation of extracted files wh… [See Man Page]'
complete -c ar -s u --description 'Update older files in the archive.'
complete -c ar -s v --description 'Give verbose output.'
complete -c ar -s x --description 'description of the archive creation and mainten… [See Man Page]'
complete -c ar -o tv -o 'l.' --description 'would have made parsing the output of ar the sa… [See Man Page]'

