# at
# Autogenerated from man page /usr/share/man/man1/at.1p.gz
# using Deroffing man parser
complete -c at -s f --description 'Specify the pathname of a file to be used as th… [See Man Page]'
complete -c at -s l --description '(The letter ell.'
complete -c at -s m --description 'Send mail to the invoking user after the at-job… [See Man Page]'
complete -c at -s q --description 'sp Specify in which queue to schedule a job for submission.'
complete -c at -s r --description 'Remove the jobs with the specified at_job_id op… [See Man Page]'
complete -c at -s t --description 'or timespec arguments, the results are unspecified.'

