# batch
# Autogenerated from man page /usr/share/man/man1/batch.1p.gz
# using Deroffing man parser
complete -c batch -o 'qb.' --description 'features were added to list and control batch w… [See Man Page]'

