# c99
# Autogenerated from man page /usr/share/man/man1/c99.1p.gz
# using Deroffing man parser
complete -c c99 -s c --description 'Suppress the link-edit phase of the compilation… [See Man Page]'
complete -c c99 -s g --description 'Produce symbolic information in the object or e… [See Man Page]'
complete -c c99 -s s --description 'Produce object or executable files, or both, fr… [See Man Page]'
complete -c c99 -s o --description 'Use the pathname outfile, instead of the default a.'
complete -c c99 -s D --description 'sp Define name as if by a C-language #define directive.'
complete -c c99 -s E --description 'Copy C-language source files to standard output… [See Man Page]'
complete -c c99 -s I --description 'Change the algorithm for searching for headers … [See Man Page]'
complete -c c99 -s L --description 'Change the algorithm of searching for the libra… [See Man Page]'
complete -c c99 -s O --description 'Specify the level of code optimization.'
complete -c c99 -s U --description 'is, if name is used in both a -U and a.'
complete -c c99 -s l --description '(The letter ell. ) Search the library named:  liblibrary.'

