# ccache-swig
# Autogenerated from man page /usr/share/man/man1/ccache-swig.1.gz
# using Deroffing man parser
complete -c ccache-swig -s h --description 'Print a options summary page.'
complete -c ccache-swig -s s --description '.'
complete -c ccache-swig -s z --description '.'
complete -c ccache-swig -s c --description '.'
complete -c ccache-swig -s C --description '.'
complete -c ccache-swig -s F --description '.'
complete -c ccache-swig -s M --description '.'
complete -c ccache-swig -s V --description 'OPTIONS These options only apply when you invok… [See Man Page]'

