# cd
# Autogenerated from man page /usr/share/man/man1/cd.1p.gz
# using Deroffing man parser
complete -c cd -s L --description 'Handle the operand dot-dot logically; symbolic … [See Man Page]'
complete -c cd -s P --description 'Handle the operand dot-dot physically; symbolic… [See Man Page]'

