# centerim
# Autogenerated from man page /usr/share/man/man1/centerim.1.gz
# using Deroffing man parser
complete -c centerim -s a -l ascii --description 'use ascii characters to draw lines and boxes.'
complete -c centerim -s h -l help --description 'display command line usage.'
complete -c centerim -s v -l version --description 'show the program version info.'
complete -c centerim -s b -l basedir --description 'specify another base directory; useful for havi… [See Man Page]'
complete -c centerim -s B -l bind --description 'tells centerim to use the specified IP address … [See Man Page]'
complete -c centerim -l no-xtitles --description 'disable title changing in xterm or screen.'
complete -c centerim -s o -l offline --description 'start with all protocols set offline  .'
complete -c centerim -s s -l send --description 'This parameter specifies the type of event you want to send.'
complete -c centerim -s p -l proto --description 'This one specifies to which IM network the dest… [See Man Page]'
complete -c centerim -s t -l to --description 'With this one you specify nickname or UIN of th… [See Man Page]'
complete -c centerim -s n -l number --description 'Using this parameter you can send SMSes to any … [See Man Page]'
complete -c centerim -s S -l status --description 'The argument parameter is a letter which indica… [See Man Page]'

