# cflow
# Autogenerated from man page /usr/share/man/man1/cflow.1p.gz
# using Deroffing man parser
complete -c cflow -s d --description 'Indicate the depth at which the flowgraph is cut off.'
complete -c cflow -s i --description 'Increase the number of included symbols.'
complete -c cflow -s I -s U --description 'by c99) is significant.'
complete -c cflow -s r --description 'Reverse the caller:callee relationship, produci… [See Man Page]'

