# chsh
# Autogenerated from man page /usr/share/man/man1/chsh.1.gz
# using Deroffing man parser
complete -c chsh -s s -l shell --description 'Specify your login shell.'
complete -c chsh -s l -l list-shells --description 'Print the list of shells listed in  /etc/shells and exit.'
complete -c chsh -s u -l help --description 'Print a usage message and exit.'
complete -c chsh -s v -l version --description 'Print version information and exit.'

