# clamconf
# Autogenerated from man page /usr/share/man/man1/clamconf.1.gz
# using Type1
complete -c clamconf -s h -l help --description 'Display help and exit.'
complete -c clamconf -s V -l version --description 'Display software version and exit.'
complete -c clamconf -s c -l config-dir --description 'Search for configuration files clamd. conf and freshclam.'
complete -c clamconf -s n -l non-default --description 'Only print non-default settings.'

