# clamdtop
# Autogenerated from man page /usr/share/man/man1/clamdtop.1.gz
# using Type1
complete -c clamdtop -s h -l help --description 'Display help information and exit.'
complete -c clamdtop -s V -l version --description 'Print version number and exit.'

