# clambc
# Autogenerated from man page /usr/share/man/man1/clambc.1.gz
# using Deroffing man parser
complete -c clambc -l help -s h --description 'Show help.'
complete -c clambc -l version -s V --description 'Show version.'
complete -c clambc -l info -s i --description 'Print information about bytecode.'
complete -c clambc -l printsrc -s p --description 'Print bytecode source.'
complete -c clambc -l trace --description 'Set bytecode trace level 0. 7 (default 7).'
complete -c clambc -l no-trace-showsource --description 'Don\'t show source line during tracing.'

