# clamdscan
# Autogenerated from man page /usr/share/man/man1/clamdscan.1.gz
# using Type1
complete -c clamdscan -s h -l help --description 'Display help information and exit.'
complete -c clamdscan -s V -l version --description 'Print version number and exit.'
complete -c clamdscan -s v -l verbose --description 'Be verbose.'
complete -c clamdscan -l quiet --description 'Be quiet - only output error messages.'
complete -c clamdscan -l stdout --description 'Write all messages (except for libclamav output… [See Man Page]'
complete -c clamdscan -l config-file --description 'Read clamd settings from FILE.'
complete -c clamdscan -s l -l log --description 'Save the scan report to FILE.'
complete -c clamdscan -s f -l file-list --description 'Scan files listed line by line in FILE.'
complete -c clamdscan -s m -l multiscan --description 'In the multiscan mode clamd will attempt to sca… [See Man Page]'
complete -c clamdscan -l remove --description 'Remove infected files.  Be careful.'
complete -c clamdscan -l move --description 'Move infected files into DIRECTORY.'
complete -c clamdscan -l no-summary --description 'Do not display summary at the end of scanning.'
complete -c clamdscan -l reload --description 'Request clamd to reload virus database.'
complete -c clamdscan -l fdpass --description 'Pass the file descriptor permissions to clamd.'

