# clipit
# Autogenerated from man page /usr/share/man/man1/clipit.1.gz
# using Deroffing man parser
complete -c clipit -s '?' -l help --description 'Show help options.'
complete -c clipit -s d -l daemon --description 'Run as daemon.'
complete -c clipit -s n -l no-icon --description 'Do not use status icon.'
complete -c clipit -s c -l clipboard --description 'Print clipboard contents.'
complete -c clipit -s p -l primary --description 'Print primary contents.'

