# column
# Autogenerated from man page /usr/share/man/man1/column.1.gz
# using Deroffing man parser
complete -c column -s c -l columns --description 'Output is formatted to a width specified as num… [See Man Page]'
complete -c column -s t -l table --description 'Determine the number of columns the input conta… [See Man Page]'
complete -c column -s s -l separator --description 'Specify table separator (default is whitespace).'
complete -c column -s x -l fillrows --description 'Fill columns before filling rows.'
complete -c column -s h -l help --description 'Print help and exit.'

