# command
# Autogenerated from man page /usr/share/man/man1/command.1p.gz
# using Deroffing man parser
complete -c command -s p --description 'Perform the command search using a default valu… [See Man Page]'
complete -c command -s v --description '(On systems supporting the User Portability Utilities option.'
complete -c command -s V --description '(On systems supporting the User Portability Utilities option.'

