# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1p.gz
# using Deroffing man parser
complete -c ctags -s v --description 'If the -v flag is given, an index of the form e… [See Man Page]'

