# cxref
# Autogenerated from man page /usr/share/man/man1/cxref.1p.gz
# using Deroffing man parser
complete -c cxref -s c --description 'Write a combined cross-reference of all input files.'
complete -c cxref -s s --description 'Operate silently; do not print input filenames.'
complete -c cxref -s o --description 'Direct output to named file.'
complete -c cxref -s w --description 'Format output no wider than num (decimal) columns.'
complete -c cxref -s D --description 'Equivalent to c99.'
complete -c cxref -s I --description 'Equivalent to c99.'
complete -c cxref -s U --description 'by c99) is significant.'

