# diff
# Autogenerated from man page /usr/share/man/man1/diff.1p.gz
# using Deroffing man parser
complete -c diff -o Cn --description 'Produce output in a form that provides n lines … [See Man Page]'
complete -c diff -s f --description 'Produce output in an alternative form, similar … [See Man Page]'
complete -c diff -o 'f.' --description '.'
complete -c diff -l - --description '> Tue Jun 19 21:41:39 PDT 1990 RATIONALE.'

