# fallocate
# Autogenerated from man page /usr/share/man/man1/fallocate.1.gz
# using Deroffing man parser
complete -c fallocate -s n -l keep-size --description 'Do not modify the apparent length of the file.'
complete -c fallocate -s p -l punch-hole --description 'Punch holes in the file, the range should not e… [See Man Page]'
complete -c fallocate -s o -l offset --description 'Specifies the beginning offset of the allocation, in bytes.'
complete -c fallocate -s l -l length --description 'Specifies the length of the allocation, in bytes.'
complete -c fallocate -s h -l help --description 'Print help and exit.'
complete -c fallocate -s V -l version --description 'Print version and exit.  AUTHORS.'

