# fc
# Autogenerated from man page /usr/share/man/man1/fc.1p.gz
# using Deroffing man parser
complete -c fc -s e --description 'Use the editor named by editor to edit the commands.'
complete -c fc -s l --description '(The letter ell.'
complete -c fc -s n --description 'Suppress command numbers when listing with -l.'
complete -c fc -s r --description 'Reverse the order of the commands listed (with … [See Man Page]'
complete -c fc -s s --description 'Re-execute the command without invoking an editor.'
complete -c fc -o number --description '.'
complete -c fc -o 'l)' -o 'l).' --description 'be accomplished by presenting to the editor all… [See Man Page]'
complete -c fc -o 's).' --description 'fc (``fix command"), but it does not meet the U… [See Man Page]'

