# file
# Autogenerated from man page /usr/share/man/man1/file.1p.gz
# using Deroffing man parser
complete -c file -s d --description 'Apply any position-sensitive default system tes… [See Man Page]'
complete -c file -s M --description 'Specify the name of a file containing position-… [See Man Page]'

