# find
# Autogenerated from man page /usr/share/man/man1/find.1p.gz
# using Deroffing man parser
complete -c find -s s --description 'not specify ls -s.'
complete -c find -o 'follow.' --description 'added for two reasons.'

