# fort77
# Autogenerated from man page /usr/share/man/man1/fort77.1p.gz
# using Deroffing man parser
complete -c fort77 -s c --description 'Suppress the link-edit phase of the compilation… [See Man Page]'
complete -c fort77 -s g --description 'Produce symbolic information in the object or e… [See Man Page]'
complete -c fort77 -s s --description 'Produce object or executable files, or both, fr… [See Man Page]'
complete -c fort77 -s o --description 'Use the pathname outfile, instead of the default a.'
complete -c fort77 -s L --description 'Change the algorithm of searching for the libra… [See Man Page]'
complete -c fort77 -s O --description 'Specify the level of code optimization.'
complete -c fort77 -s w --description 'Suppress warnings.'
complete -c fort77 -s l --description '(The letter ell. ) Search the library named:  liblibrary.'
complete -c fort77 -o 'c;' --description 'SYNOPSIS shows all of the options separately to… [See Man Page]'

