# gaupol
# Autogenerated from man page /usr/share/man/man1/gaupol.1.gz
# using Deroffing man parser
complete -c gaupol -s h -l help --description 'Show command line options.'
complete -c gaupol -l version --description 'Show version number.'
complete -c gaupol -s e -l encoding --description 'Set the character encoding to use for opening files.'
complete -c gaupol -l list-encodings --description 'List possible character encodings to use with --encoding.'
complete -c gaupol -s t -l translation-file --description 'Open translation file.'
complete -c gaupol -s a -l align-method --description 'Method used to align translation file\'s subtitl… [See Man Page]'
complete -c gaupol -s v -l video-file --description 'Select video file.'

