# gdome-config
# Autogenerated from man page /usr/share/man/man1/gdome-config.1.gz
# using Deroffing man parser
complete -c gdome-config -l version --description 'Print the currently installed version of gdome2… [See Man Page]'
complete -c gdome-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c gdome-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c gdome-config -l prefix --description 'If specified, use DIR instead of the installati… [See Man Page]'
complete -c gdome-config -l exec-prefix --description 'If specified, use DIR instead of the installati… [See Man Page]'
complete -c gdome-config -l help --description 'Print a short help text and exit.'

