# gelemental
# Autogenerated from man page /usr/share/man/man1/gelemental.1.gz
# using Deroffing man parser
complete -c gelemental -l help --description 'Display a summary of available command-line options.'
complete -c gelemental -s p -l print --description 'Print information on the indicated element to standard output.'
complete -c gelemental -s s -l show --description 'Show the properties dialog for the indicated element.'
complete -c gelemental -s i -l interactive --description 'Display the table even if data have been printe… [See Man Page]'

