# gem2arch
# Autogenerated from man page /usr/share/man/man1/gem2arch.1.gz
# using Deroffing man parser
complete -c gem2arch -s o --description 'Writes PKGBUILD to DIRECTORY instead of GEM.'
complete -c gem2arch -s d --description 'Does not create the PKGBUILD but rather simply … [See Man Page]'
complete -c gem2arch -s q --description 'Removes any warning or information messages tha… [See Man Page]'

