# genmap
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/genmap.1
# using Deroffing man parser
complete -c genmap -s D --description 'Show debug information.'
complete -c genmap -s o --description 'Output on mapfile.'
complete -c genmap -s i --description 'Library to inspect SEE ALSO root(1), rlibmap(1).'

