# genreflex-rootcint
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/genreflex-rootcint.1
# using Deroffing man parser
complete -c genreflex-rootcint -o gccxml --description 'is specified, and  gccxml (1) is found.'

