# genreflex
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/genreflex.1
# using Deroffing man parser
complete -c genreflex -s s -l selection_file --description 'Class selection file to specify for which class… [See Man Page]'
complete -c genreflex -s o -l output --description 'Output file name.'
complete -c genreflex -l pool --description 'Generate minimal dictionary required for POOL persistence.'
complete -c genreflex -l deep --description 'Generate dictionary for all dependend classes.'
complete -c genreflex -l split --description 'Generate separate file for stub functions.'
complete -c genreflex -l reflex --description 'Generate Reflex dictionaries.'
complete -c genreflex -l comments --description 'Add end-of-line comments in data and functions … [See Man Page]'
complete -c genreflex -l no_membertypedefs --description 'Disable the definition of class member typedefs.'
complete -c genreflex -l fail_on_warnings --description 'The genreflex command fails (retuns the value 1… [See Man Page]'
complete -c genreflex -l gccxmlpath --description 'Path path where the gccxml(1) tool is installed.'
complete -c genreflex -s c -l capabilities --description 'Generate the capabilities file to be used by th… [See Man Page]'
complete -c genreflex -l rootmap --description 'Generate the rootmap file to be used by ROOT/CINT.'
complete -c genreflex -l rootmap-lib --description 'Library name for the rootmap file.'
complete -c genreflex -l debug --description 'Print extra debug information while processing.'
complete -c genreflex -l quiet --description 'No not print informational messages.'
complete -c genreflex -s h -l help --description 'Print help.'

