# get
# Autogenerated from man page /usr/share/man/man1/get.1p.gz
# using Deroffing man parser
complete -c get -s r --description 'Indicate the SCCS Identification String (SID) o… [See Man Page]'
complete -c get -s c --description 'Indicate the cutoff date-time, in the form:  . sp . RS .'
complete -c get -s e --description 'Indicate that the get is for the purpose of edi… [See Man Page]'
complete -c get -s b --description 'Use with the -e option to indicate that the new… [See Man Page]'
complete -c get -s i --description 'Indicate a list of deltas to be included (force… [See Man Page]'
complete -c get -s x --description 'Indicate a list of deltas to be excluded (force… [See Man Page]'
complete -c get -s k --description 'Suppress replacement of identification keywords… [See Man Page]'
complete -c get -s l --description 'Write a delta summary into an l-file.'
complete -c get -s L --description 'Write a delta summary to standard output.'
complete -c get -s p --description 'Write the text retrieved from the SCCS file to … [See Man Page]'
complete -c get -s s --description 'Suppress all informative output normally writte… [See Man Page]'
complete -c get -s m --description 'Precede each text line retrieved from the SCCS … [See Man Page]'
complete -c get -s n --description 'Precede each generated text line with the %M% i… [See Man Page]'
complete -c get -s g --description 'Suppress the actual retrieval of text from the SCCS file.'
complete -c get -s t --description 'Use to access the most recently created (top) d… [See Man Page]'

