# git-remote-helpers
# Autogenerated from man page /usr/share/man/man1/git-remote-helpers.1.gz
# using Deroffing man parser
complete -c git-remote-helpers -l export-marks --description 'in git-fast-export(1).  import-marks <file>.'
complete -c git-remote-helpers -l import-marks --description 'in git-fast-export(1).  COMMANDS.'

