# grab_color_image
# Autogenerated from man page /usr/share/man/man1/grab_color_image.1.gz
# using Deroffing man parser
complete -c grab_color_image -l guid --description 'specifies camera to use.'
complete -c grab_color_image -l help --description 'print help message.'

