# grub-mkstandalone
# Autogenerated from man page /usr/share/man/man1/grub-mkstandalone.1.gz
# using Deroffing man parser
complete -c grub-mkstandalone -s h -l help --description 'print this message and exit.'
complete -c grub-mkstandalone -s v -l version --description 'print the version information and exit.'
complete -c grub-mkstandalone -s o -l output --description 'save output in FILE [required].'
complete -c grub-mkstandalone -s d -l directory --description 'use images and modules under DIR [default=/usr/… [See Man Page]'
complete -c grub-mkstandalone -s O -l format --description 'generate an image in FORMAT P available formats… [See Man Page]'
complete -c grub-mkstandalone -s C -l compression --description 'choose the compression to use.'
complete -c grub-mkstandalone -l modules --description 'pre-load specified modules MODULES.'
complete -c grub-mkstandalone -l grub-mkimage --description 'use FILE as grub-mkimage REPORTING BUGS Report … [See Man Page]'

