# gsl-config
# Autogenerated from man page /usr/share/man/man1/gsl-config.1.gz
# using Deroffing man parser
complete -c gsl-config -l version --description 'Print the currently installed version of GSL on… [See Man Page]'
complete -c gsl-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c gsl-config -l libs-without-cblas --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c gsl-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c gsl-config -l prefix --description 'Show the GSL installation prefix.'

