# hash
# Autogenerated from man page /usr/share/man/man1/hash.1p.gz
# using Deroffing man parser
complete -c hash -s r --description 'Forget all previously remembered utility locations.'
complete -c hash -s t --description 'search are not listed by the hash command.'

