# hidd
# Autogenerated from man page /usr/share/man/man1/hidd.1.gz
# using Deroffing man parser
complete -c hidd -s i --description 'Local HCI device or BD Address.'
complete -c hidd -s t --description 'Set idle timeout (in minutes).'
complete -c hidd -s n -l nodaemon --description 'Don\'t fork daemon to background.'
complete -c hidd -s h -l help --description 'Display help . SS "Commands:".'
complete -c hidd -l server --description 'Start HID server.'
complete -c hidd -l search --description 'Search for HID devices.'
complete -c hidd -l connect --description 'Connect remote HID device.'
complete -c hidd -l kill --description 'Terminate HID connection.'
complete -c hidd -l killall --description 'Terminate all connections.'
complete -c hidd -l show --description 'List current HID connections.'

