# hist2workspace
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/hist2workspace.1
# using Deroffing man parser
complete -c hist2workspace -o standard_form --description 'default model, which creates an extended PDF th… [See Man Page]'
complete -c hist2workspace -o number_counting_form --description 'this was the original model in 5. 28 (without patches).'

