# hwloc-assembler
# Autogenerated from man page /usr/share/man/man1/hwloc-assembler.1.gz
# using Deroffing man parser
complete -c hwloc-assembler -s n -l name --description 'Set <name> in the AssemblerName info attribute … [See Man Page]'
complete -c hwloc-assembler -s f -l force --description 'Ignore errors while reading input files.'
complete -c hwloc-assembler -s v -l verbose --description 'Verbose messages.  DESCRIPTION.'

