# hwloc-annotate
# Autogenerated from man page /usr/share/man/man1/hwloc-annotate.1.gz
# using Deroffing man parser
complete -c hwloc-annotate -l ci --description 'Clear the existing info attributes in the targe… [See Man Page]'

