# hwloc-bind
# Autogenerated from man page /usr/share/man/man1/hwloc-bind.1.gz
# using Deroffing man parser
complete -c hwloc-bind -l cpubind --description 'Use following arguments for CPU binding (default).'
complete -c hwloc-bind -l membind --description 'Use following arguments for memory binding.'
complete -c hwloc-bind -l mempolicy --description 'Change the memory binding policy.'
complete -c hwloc-bind -l get --description 'Report the current bindings.'
complete -c hwloc-bind -l get-last-cpu-location --description 'Report the last processors where the process ran.'
complete -c hwloc-bind -l single --description 'Bind on a single CPU to prevent migration.'
complete -c hwloc-bind -l strict --description 'Require strict binding.'
complete -c hwloc-bind -l pid --description 'Operate on pid <pid>.'
complete -c hwloc-bind -s p -l physical --description 'take OS/physical indexes instead of logical indexes.'
complete -c hwloc-bind -s l -l logical --description 'take logical indexes instead of physical/OS indexes (default).'
complete -c hwloc-bind -l taskset --description 'Display CPU set strings in the format recognize… [See Man Page]'
complete -c hwloc-bind -s f -l force --description 'Launch the executable even if binding failed.'
complete -c hwloc-bind -s q -l quiet --description 'Hide non-fatal error messages.'
complete -c hwloc-bind -s v -l verbose --description 'Verbose output.'
complete -c hwloc-bind -l version --description 'Report version and exit.  DESCRIPTION.'

