# hwloc-calc
# Autogenerated from man page /usr/share/man/man1/hwloc-calc.1.gz
# using Deroffing man parser
complete -c hwloc-calc -s p -l physical --description 'Use OS/physical indexes instead of logical inde… [See Man Page]'
complete -c hwloc-calc -s l -l logical --description 'Use logical indexes instead of physical/OS inde… [See Man Page]'
complete -c hwloc-calc -l pi -l physical-input --description 'Use OS/physical indexes instead of logical indexes for input.'
complete -c hwloc-calc -l li -l logical-input --description 'Use logical indexes instead of physical/OS inde… [See Man Page]'
complete -c hwloc-calc -l po --description 'Use OS/physical indexes instead of logical indexes for output.'
complete -c hwloc-calc -l lo -l logical-output --description 'Use logical indexes instead of physical/OS inde… [See Man Page]'
complete -c hwloc-calc -s N -l number-of --description 'Report the number of objects of the given type … [See Man Page]'
complete -c hwloc-calc -s I -l intersect --description 'Find the list of objects of the given type or d… [See Man Page]'
complete -c hwloc-calc -s H -l hierarchical --description 'Find the list of objects of type <type2> that i… [See Man Page]'
complete -c hwloc-calc -l largest --description 'Report (in a human readable format) the list of… [See Man Page]'
complete -c hwloc-calc -l sep --description 'Change the field separator in the output.'
complete -c hwloc-calc -l single --description 'Singlify the output to a single CPU.'
complete -c hwloc-calc -l taskset --description 'Display CPU set strings in the format recognize… [See Man Page]'
complete -c hwloc-calc -l restrict --description 'Restrict the topology to the given cpuset.'
complete -c hwloc-calc -s i -l input --description 'Read topology from XML file <file> (instead of … [See Man Page]'
complete -c hwloc-calc -l if -l input-format --description 'Enforce the input in the given format, among xm… [See Man Page]'
complete -c hwloc-calc -s q -l quiet --description 'Hide non-fatal error messages.'
complete -c hwloc-calc -s v -l verbose --description 'Verbose output.'
complete -c hwloc-calc -l version --description 'Report version and exit.  DESCRIPTION.'

