# hwloc-distances
# Autogenerated from man page /usr/share/man/man1/hwloc-distances.1.gz
# using Deroffing man parser
complete -c hwloc-distances -s l -l logical --description 'Display hwloc logical indexes (default) instead… [See Man Page]'
complete -c hwloc-distances -s p -l physical --description 'Display OS/physical indexes instead of hwloc logical indexes.'
complete -c hwloc-distances -s i -l input --description 'Read topology from XML file <file> (instead of … [See Man Page]'
complete -c hwloc-distances -l if -l input-format --description 'Enforce the input in the given format, among xm… [See Man Page]'
complete -c hwloc-distances -l restrict --description 'Restrict the topology to the given cpuset.'
complete -c hwloc-distances -s v -l verbose --description 'Verbose messages.'
complete -c hwloc-distances -l version --description 'Report version and exit.  DESCRIPTION.'

