# hwloc-ps
# Autogenerated from man page /usr/share/man/man1/hwloc-ps.1.gz
# using Deroffing man parser
complete -c hwloc-ps -s a --description 'list all processes, even those that are not bou… [See Man Page]'
complete -c hwloc-ps -s p -l physical --description 'report OS/physical indexes instead of logical indexes.'
complete -c hwloc-ps -s l -l logical --description 'report logical indexes instead of physical/OS i… [See Man Page]'
complete -c hwloc-ps -s c -l cpuset --description 'show process bindings as cpusets instead of objects.'
complete -c hwloc-ps -s t -l threads --description 'show threads inside processes.'
complete -c hwloc-ps -l whole-system --description 'Do not consider administration limitations.'
complete -c hwloc-ps -l pid-cmd --description 'Append the output of the given command to each PID line.'

