# hwloc-assembler-remote
# Autogenerated from man page /usr/share/man/man1/hwloc-assembler-remote.1.gz
# using Deroffing man parser
complete -c hwloc-assembler-remote -l ssh --description 'Use the given ssh command (and options) to conn… [See Man Page]'
complete -c hwloc-assembler-remote -l lstopo-path --description 'Use the given path as the remote lstopo command… [See Man Page]'
complete -c hwloc-assembler-remote -l lstopo-opts --description 'Pass the given lstopo options when gathering remote topologies.'
complete -c hwloc-assembler-remote -l show --description 'Display the resulting topology before exit.'
complete -c hwloc-assembler-remote -s v -l verbose --description 'Verbose messages.  DESCRIPTION.'

