# hwloc-distrib
# Autogenerated from man page /usr/share/man/man1/hwloc-distrib.1.gz
# using Deroffing man parser
complete -c hwloc-distrib -l single --description 'Singlify each output to a single CPU.'
complete -c hwloc-distrib -l taskset --description 'Show CPU set strings in the format recognized b… [See Man Page]'
complete -c hwloc-distrib -s v -l verbose --description 'Verbose messages.'
complete -c hwloc-distrib -s i -l input --description 'Read topology from XML file <file> (instead of … [See Man Page]'
complete -c hwloc-distrib -l if -l input-format --description 'Enforce the input in the given format, among xm… [See Man Page]'
complete -c hwloc-distrib -l ignore --description 'Ignore all objects of type <type> in the topology.'
complete -c hwloc-distrib -l from --description 'Distribute starting from objects of the given t… [See Man Page]'
complete -c hwloc-distrib -l top --description 'Distribute down to objects of the given type in… [See Man Page]'
complete -c hwloc-distrib -l at --description 'Distribute among objects of the given type.'
complete -c hwloc-distrib -l restrict --description 'Restrict the topology to the given cpuset.'
complete -c hwloc-distrib -l version --description 'Report version and exit.  DESCRIPTION.'

