# idevicebackup2
# Autogenerated from man page /usr/share/man/man1/idevicebackup2.1.gz
# using Deroffing man parser
complete -c idevicebackup2 -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c idevicebackup2 -s d -l debug --description 'enable communication debugging.'
complete -c idevicebackup2 -s h -l help --description 'prints usage information.'

