# idnconv
# Autogenerated from man page /usr/share/man/man1/idnconv.1.gz
# using Deroffing man parser
complete -c idnconv -o in -s i --description 'Specify the codeset name of the input text.'
complete -c idnconv -o out -s o --description 'Specify the codeset name of the output text.'
complete -c idnconv -o conf -s c --description 'Specify the pathname of idnkit configuration file (``idn.'
complete -c idnconv -o noconf -s C --description 'Specify that no configuration file is to be used.'
complete -c idnconv -o reverse -s r --description 'Specify reverse conversion mode.'
complete -c idnconv -o nameprep -s n --description 'Specify the version of NAMEPREP.'
complete -c idnconv -o nonameprep -s N --description 'Specify to skip NAMEPREP process (or NAMEPREP v… [See Man Page]'
complete -c idnconv -o localmap --description 'Specify the name of local mapping rule.'
complete -c idnconv -o nounassigncheck -s U --description 'Skip unassigned codepoint check.'
complete -c idnconv -o nobidicheck -s B --description 'Skip bidi character check.'
complete -c idnconv -o nolengthcheck --description 'Do not check label length of normal conversion result.'
complete -c idnconv -o noasciicheck -s A --description 'Do not check ASCII range characters.'
complete -c idnconv -o noroundtripcheck --description 'Do not perform round trip check.'
complete -c idnconv -o delimiter --description 'Specify the character to be mapped to domain na… [See Man Page]'
complete -c idnconv -o whole -s w --description 'Perform local mapping, nameprep and conversion … [See Man Page]'
complete -c idnconv -o alias -s a --description 'Specify a codeset alias file.'
complete -c idnconv -o flush --description 'Force line-buffering mode.'
complete -c idnconv -o version -s v --description 'Print version information and quit.'

