# irunner2
# Autogenerated from man page /usr/share/man/man1/irunner2.1.gz
# using Deroffing man parser
complete -c irunner2 -s h -l help --description 'show this help message and exit.'
complete -c irunner2 -l ipython --description 'IPython interactive runner (default).'
complete -c irunner2 -l python --description 'Python interactive runner.'
complete -c irunner2 -l sage --description 'SAGE interactive runner.  EXAMPLE irunner.'

