# jay
# Autogenerated from man page /usr/share/man/man1/jay.1.gz
# using Deroffing man parser
complete -c jay -s b --description 'The  -b option changes the prefix prepended to … [See Man Page]'
complete -c jay -s c --description 'The  -c  option makes jay generate C# code inst… [See Man Page]'
complete -c jay -s t --description 'The  -t option arranges for debugging informati… [See Man Page]'
complete -c jay -s v --description 'The  -v option causes a human-readable descript… [See Man Page]'
complete -c jay -s p --description 'The.'

