# kmymoney
# Autogenerated from man page /usr/share/man/man1/kmymoney.1.gz
# using Deroffing man parser
complete -c kmymoney -s n --description 'Start without opening a file.'
complete -c kmymoney -l help --description 'Show help about options.'
complete -c kmymoney -l help-qt --description 'Show Qt specific options.'
complete -c kmymoney -l help-kde --description 'Show KDE specific options.'
complete -c kmymoney -l help-all --description 'Show all options.'
complete -c kmymoney -l author --description 'Show author information.'
complete -c kmymoney -s v -l version --description 'Show version information.'
complete -c kmymoney -l license --description 'Show license information.'

