# ktikz
# Autogenerated from man page /usr/share/man/man1/ktikz.1.gz
# using Deroffing man parser
complete -c ktikz -l help --description 'Show help about options.'
complete -c ktikz -l help-qt --description 'Show Qt specific options.'
complete -c ktikz -l help-kde --description 'Show KDE specific options.'
complete -c ktikz -l help-all --description 'Show all options.'
complete -c ktikz -l author --description 'Show author information.'
complete -c ktikz -s v -l version --description 'Show version information.'
complete -c ktikz -l license --description 'Show license information.'

