# ktoblzcheck
# Autogenerated from man page /usr/share/man/man1/ktoblzcheck.1.gz
# using Deroffing man parser
complete -c ktoblzcheck -l returncode --description 'If given, the result is returned via the return… [See Man Page]'
complete -c ktoblzcheck -l file --description 'Specifies the file with the bankdata.'

