# latexdiff-vc
# Autogenerated from man page /usr/share/man/man1/latexdiff-vc.1.gz
# using Type1
complete -c latexdiff-vc -l rcs -l svn -l cvs --description 'Set the version system.'
complete -c latexdiff-vc -s r -s r -l revision -l revision --description 'Choose revision (under \\s-1RCS\\s0, \\s-1CVS\\s0 or \\s-1SVN\\s0).'
complete -c latexdiff-vc -s d -l dir -s d -l dir --description 'Rather than appending the string \\f(CW\\*(C`diff… [See Man Page]'
complete -c latexdiff-vc -l ps -l postscript --description 'Generate postscript output from difference file.'
complete -c latexdiff-vc -l pdf --description 'Generate pdf output from difference file using … [See Man Page]'
complete -c latexdiff-vc -l force --description 'Overwrite existing diff files without asking for confirmation.'
complete -c latexdiff-vc -l help -s h --description 'Show help text.'

