# latexrevise
# Autogenerated from man page /usr/share/man/man1/latexrevise.1.gz
# using Type1
complete -c latexrevise -s a -l accept --description 'Run in \\s-1ACCEPT\\s0 mode (delete all blocks ma… [See Man Page]'
complete -c latexrevise -s d -l decline --description 'Run in \\s-1DECLINE\\s0 mode (delete all blocks m… [See Man Page]'
complete -c latexrevise -s s -l simplify --description 'Run in \\s-1SIMPLIFY\\s0 mode (Keep all \\f(CW\\*(C… [See Man Page]'
complete -c latexrevise -s c -l comment --description 'Remove \\f(CW\\*(C`cmd{. }\\*(C\' sequences.'
complete -c latexrevise -s e -l comment-environment --description 'Remove explicit annotation environments from the text, i. e.'
complete -c latexrevise -s m -l markup --description 'Remove the markup command \\f(CW\\*(C`cmd\\*(C\' bu… [See Man Page]'
complete -c latexrevise -s n -l markup-environment --description 'Similarly, remove \\f(CW\\*(C`begin{envir}\\*(C\' a… [See Man Page]'
complete -c latexrevise -s V -l verbose --description 'Verbose output.'

