# lavplay
# Autogenerated from man page /usr/share/man/man1/lavplay.1.gz
# using Deroffing man parser
complete -c lavplay -o p/--playback --description 'The playback mode to be used.'
complete -c lavplay -o Z/--full-screen --description 'Full-screen playback.'
complete -c lavplay -l size --description 'Size of the video window (default: size of the … [See Man Page]'
complete -c lavplay -o a/--audio --description 'When play audio, 0 means never, or sum of   1: … [See Man Page]'
complete -c lavplay -o z/--zoom --description 'Zooms the video to fit the screen as good as possible.'
complete -c lavplay -s x --description 'Exchange fields of an interlaced video.'
complete -c lavplay -o s/--skip --description 'Skip <num> seconds of video at the beginning.'
complete -c lavplay -o x/--exchange-fields --description 'Invert field order (for videos which are record… [See Man Page]'
complete -c lavplay -o F/--flicker --description 'Disable stills flicker reduction.'
complete -c lavplay -o c/--synchronization --description 'Enables (1) or disables (0) the use of sync corrections.'
complete -c lavplay -o H/--H-offset -o V/--V-offset --description 'Horizontal (-H) and vertical (-V) offset when u… [See Man Page]'
complete -c lavplay -l s-x-offset -l s-y-offset --description 'Offset for the video window (from top left scre… [See Man Page]'
complete -c lavplay -l display --description 'When using hardware fullsreen video playback (-… [See Man Page]'
complete -c lavplay -o q/--no-quit --description 'Makes lavplay stay alive at the end of the vide… [See Man Page]'
complete -c lavplay -o g/--gui-mode --description 'Enables GUI-mode.  This is used by glav and Linux Video Studio.'
complete -c lavplay -o P/--preserve-pathnames --description 'This is used by glav and Linux Video Studio.'
complete -c lavplay -o U/--use-write --description 'Use the write() system call rather than the mma… [See Man Page]'
complete -c lavplay -o n/--mjpeg-buffers --description 'Number of MJPEG-buffers.  Default is 32.'
complete -c lavplay -o v/--verbose --description 'Verbosity level (0, 1 or 2).'

