# ldns-walk
# Autogenerated from man page /usr/share/man/man1/ldns-walk.1.gz
# using Deroffing man parser
complete -c ldns-walk -s f --description 'Do a \'full\' zone walk; by default, ldns-walk wi… [See Man Page]'
complete -c ldns-walk -s s --description 'Start the walk with this owner name.'

