# lex
# Autogenerated from man page /usr/share/man/man1/lex.1p.gz
# using Deroffing man parser
complete -c lex -s n --description 'Suppress the summary of statistics usually writ… [See Man Page]'
complete -c lex -s t --description 'Write the resulting program to standard output instead of lex.'
complete -c lex -s v --description 'Write a summary of lex statistics to the standard output.'

