# llvm-ranlib
# Autogenerated from man page /usr/share/man/man1/llvm-ranlib.1.gz
# using Deroffing man parser
complete -c llvm-ranlib -l version --description 'Print the version of llvm-ranlib and exit witho… [See Man Page]'
complete -c llvm-ranlib -o help --description 'Print usage help for llvm-ranlib and exit witho… [See Man Page]'

