# locale
# Autogenerated from man page /usr/share/man/man1/locale.1p.gz
# using Deroffing man parser
complete -c locale -s a --description 'Write information about all available public locales.'
complete -c locale -s c --description 'Write the names of selected locale categories; … [See Man Page]'
complete -c locale -s k --description 'Write the names and values of selected keywords.'
complete -c locale -s m --description 'Write names of available charmaps; see the Base… [See Man Page]'

