# loginctl
# Autogenerated from man page /usr/share/man/man1/loginctl.1.gz
# using Deroffing man parser
complete -c loginctl -l help -s h --description 'Prints a short help text and exits.'
complete -c loginctl -l version --description 'Prints a short version string and exits.'
complete -c loginctl -l property -s p --description 'When showing session/user properties, limit dis… [See Man Page]'
complete -c loginctl -l all -s a --description 'When showing unit/job/manager properties, show … [See Man Page]'
complete -c loginctl -l no-pager --description 'Do not pipe output into a pager.'
complete -c loginctl -l no-ask-password --description 'Don\\*(Aqt query the user for authentication for… [See Man Page]'
complete -c loginctl -l kill-who --description 'When used with kill-session, choose which processes to kill.'
complete -c loginctl -l signal -s s --description 'When used with kill-session or kill-user, choos… [See Man Page]'
complete -c loginctl -s H -l host --description 'Execute operation remotely.'
complete -c loginctl -s P -l privileged --description 'Acquire privileges via PolicyKit before executi… [See Man Page]'
complete -c loginctl -l 'no-pager.' --description '.'

