# lrelease
# Autogenerated from man page /opt/qt/man/man1/lrelease.1.gz
# using Deroffing man parser
complete -c lrelease -o help --description 'Display the usage and exit.'
complete -c lrelease -o nocompress --description 'Do not compress the . qm files.'
complete -c lrelease -o verbose --description 'Explain what is being done.'
complete -c lrelease -o version --description 'Display the version of lrelease and exit.'

