# ls
# Autogenerated from man page /usr/share/man/man1/ls.1p.gz
# using Deroffing man parser
complete -c ls -o 'a;' --description 'order is the order in which entries appear in the directory.'
complete -c ls -o 'C)' --description 'or invalid, an implementation-defined number of… [See Man Page]'
complete -c ls -o laRF --description 'total 11 drwxr-xr-x   3 hlj      prog          … [See Man Page]'
complete -c ls -o rwxr--r-- --description 'a/b: total 4 drwxr-xr-x   2 hlj      prog      … [See Man Page]'
complete -c ls -o rw-r--r-- --description 'RATIONALE.'

