# lspst
# Autogenerated from man page /usr/share/man/man1/lspst.1.gz
# using Deroffing man parser
complete -c lspst -s V --description 'Show program version and exit.'
complete -c lspst -s d --description 'Specify name of debug log file.'
complete -c lspst -s h --description 'Show summary of options and exit.'

