# lupdate
# Autogenerated from man page /opt/qt/man/man1/lupdate.1.gz
# using Deroffing man parser
complete -c lupdate -o help --description 'Display the usage and exit.'
complete -c lupdate -o noobsolete --description 'Drop all obsolete strings.'
complete -c lupdate -o verbose --description 'Explain what is being done.'
complete -c lupdate -o version --description 'Display the version of lupdate and exit.'

