# lyx
# Autogenerated from man page /usr/share/man/man1/lyx.1.gz
# using Deroffing man parser
complete -c lyx -o help --description 'summarizes LyX usage.'
complete -c lyx -o version --description 'provides version information on the build of LyX.'
complete -c lyx -o sysdir --description 'sets system directory.  Normally not needed.'
complete -c lyx -o userdir --description 'sets user directory.'
complete -c lyx -o geometry --description 'set geometry of the main window.'
complete -c lyx -o dbg --description 'where feature is a name or number.'
complete -c lyx -s x --description 'where command is a lyx command.'
complete -c lyx -s e --description 'where fmt is the export format of choice (latex… [See Man Page]'
complete -c lyx -s i --description 'where fmt is the import format of choice and file.'
complete -c lyx -s f --description 'where what is is either "all", "main" or "none".'
complete -c lyx -s n --description 'open documents passed as arguments in a new ins… [See Man Page]'
complete -c lyx -s r --description 'by using the lyxpipe, ask an already running in… [See Man Page]'
complete -c lyx -o batch --description 'causes LyX to run the given commands without op… [See Man Page]'

