# lyxclient
# Autogenerated from man page /usr/share/man/man1/lyxclient.1.gz
# using Deroffing man parser
complete -c lyxclient -s p --description 'specify the pid of the running LyX process to w… [See Man Page]'
complete -c lyxclient -s a --description 'specify explicitly which socket special file should be used.'
complete -c lyxclient -s t --description 'if LyX is configured to use a temporary directo… [See Man Page]'
complete -c lyxclient -s c --description 'send a single command, print LyX information to… [See Man Page]'
complete -c lyxclient -s g --description 'this is simply a wrapper for the command \'serve… [See Man Page]'
complete -c lyxclient -s n --description 'when starting communication, lyxclient sends an… [See Man Page]'
complete -c lyxclient -s h --description 'print the lyxclient version and summarize its usage.'

