# m-tx
# Autogenerated from man page /usr/share/man/man1/m-tx.1.gz
# using Deroffing man parser
complete -c m-tx -s v --description 'output program name and version number, and quit.'
complete -c m-tx -s h --description 'output usage summary and quit.'
complete -c m-tx -s l --description 'changes the TeX processor to  latex (1) or  pdflatex (1).'
complete -c m-tx -s p --description 'changes the TeX processor to   pdfetex (1)  or … [See Man Page]'
complete -c m-tx -s d --description 'changes the dvi processor to  dvipdfm (1).'
complete -c m-tx -s s --description 'stops processing at the dvi file.'
complete -c m-tx -s t --description 'stops processing at the tex (and midi) files.'
complete -c m-tx -s m --description 'stops processing at the pmx file.'
complete -c m-tx -s i --description 'retain intermediate files.'
complete -c m-tx -s f --description 'default processing.'

