# mailx
# Autogenerated from man page /usr/share/man/man1/mailx.1p.gz
# using Deroffing man parser
complete -c mailx -o 'c.)' --description 'variable is set, each unescaped occurrence of \'… [See Man Page]'
complete -c mailx -o 'f.' --description 'and users remain portable.'

