# mathmlviewer
# Autogenerated from man page /usr/share/man/man1/mathmlviewer.1.gz
# using Deroffing man parser
complete -c mathmlviewer -s v -l version --description 'Output version information.'
complete -c mathmlviewer -s d -l debug --description 'Debug mode.'
complete -c mathmlviewer -s h -l help --description 'This small usage guide.'
complete -c mathmlviewer -l 'verbose[' --description 'Display messages AUTHORS Written by Luca Padovani.'

