# mkfifo
# Autogenerated from man page /usr/share/man/man1/mkfifo.1p.gz
# using Deroffing man parser
complete -c mkfifo -s p --description 'that created intermediate directories leading u… [See Man Page]'

