# mkoctfile
# Autogenerated from man page /usr/share/man/man1/mkoctfile.1.gz
# using Deroffing man parser
complete -c mkoctfile -s h -s '?' -l help --description 'Print help message.'
complete -c mkoctfile -o Idir --description 'Add include directory dir to compile commands.'
complete -c mkoctfile -o idirafterdir --description 'Add include directory to second include search path after \'-I\'.'
complete -c mkoctfile -o Ddef --description 'Add definition def to compiler command.'
complete -c mkoctfile -o llib --description 'Add library lib to link command.'
complete -c mkoctfile -o Ldir --description 'Add library directory dir to link command.'
complete -c mkoctfile -o Rdir --description 'Pass -Rdir to link command.'
complete -c mkoctfile -s g --description 'Enable debugging option for all compilers.'
complete -c mkoctfile -o pthread --description 'Add -pthread to link command.'
complete -c mkoctfile -o 'W...' --description 'Pass flags to the compiler such as -Wa,OPTION.'
complete -c mkoctfile -o Wl --description 'Pass flags to the linker such as -Wl,-rpath=.'
complete -c mkoctfile -s M -l depend --description 'Generate dependency files (. d) for C and C++ source files.'
complete -c mkoctfile -s c --description 'Compile but do not link.'
complete -c mkoctfile -l link-stand-alone --description 'Link a stand-alone executable file.'
complete -c mkoctfile -s s -l strip --description 'Strip the output file.'
complete -c mkoctfile -l mex --description 'Create a MEX file.   Set the default output extension to . mex.'
complete -c mkoctfile -s o -l output --description 'Output file name.   Default extension is . oct (or .'
complete -c mkoctfile -s p -l print --description 'Print configuration variable VAR.   Recognized variables are: .'
complete -c mkoctfile -s v -l verbose --description 'Echo commands as they are executed.'

