# more
# Autogenerated from man page /usr/share/man/man1/more.1p.gz
# using Deroffing man parser
complete -c more -s e --description 'By default, more shall exit immediately after w… [See Man Page]'
complete -c more -s i --description 'Perform pattern matching in searches without re… [See Man Page]'
complete -c more -s n --description 'Specify the number of lines per screenful.'
complete -c more -s t --description 'Write the screenful of the file containing the … [See Man Page]'

