# most
# Autogenerated from man page /usr/share/man/man1/most.1.gz
# using Deroffing man parser
complete -c most -s 1 --description 'VT100 mode.   This is meaningful only on VMS systems.'
complete -c most -s b --description 'Binary mode.'
complete -c most -s k --description '\\"`Kanji\' option. \\"Ordinarily, . \\" most .'
complete -c most -s C --description 'Disable color support.'
complete -c most -s d --description 'Omit the backslash mark used to denote a wrapped line.'
complete -c most -s M --description 'Disable the use of mmap.'
complete -c most -s s --description 'Squeeze.'
complete -c most -s z --description 'option turns off gunzip-on-the-fly.'
complete -c most -s v --description 'Display control characters as in `^A\' for control A.'
complete -c most -s t --description 'Display tabs as `^I\'.'
complete -c most -s c --description 'Make searches case sensitive.  By default, they are not.'
complete -c most -s u --description 'Disable UTF-8 mode even if the locale dictates it.'
complete -c most -s w --description 'option may be used to override this feature.'

