# mpicxx
# Autogenerated from man page /usr/share/man/man1/mpicxx.1.gz
# using Deroffing man parser
complete -c mpicxx -l showme --description 'This option comes in several different variants (see below).'
complete -c mpicxx -l showme:compile --description 'Output the compiler flags that would have been … [See Man Page]'
complete -c mpicxx -l showme:link --description 'Output the linker flags that would have been su… [See Man Page]'
complete -c mpicxx -l showme:command --description 'Outputs the underlying C++ compiler command (wh… [See Man Page]'
complete -c mpicxx -l showme:incdirs --description 'Outputs a space-delimited (but otherwise undeco… [See Man Page]'
complete -c mpicxx -l showme:libdirs --description 'Outputs a space-delimited (but otherwise undeco… [See Man Page]'
complete -c mpicxx -l showme:libs --description 'Outputs a space-delimited (but otherwise undeco… [See Man Page]'
complete -c mpicxx -l showme:version --description 'Outputs the version number of Open MPI.'
complete -c mpicxx -o m64 --description 'build, but can be activated (for example, in a … [See Man Page]'

