# mplex
# Autogenerated from man page /usr/share/man/man1/mplex.1.gz
# using Deroffing man parser
complete -c mplex -s o -l output --description 'This mandatory option sets the pattern for the … [See Man Page]'
complete -c mplex -s v -l verbose --description 'Set verbosity level to num:  0 - warnings and e… [See Man Page]'
complete -c mplex -s '?' -l help --description 'Display a synopsis of the command syntax.'
complete -c mplex -s f -l format --description 'This command allows one of a number of convenie… [See Man Page]'
complete -c mplex -s W -l workarounds --description '.'
complete -c mplex -s i -l vdr-index --description 'This tells mplex to generate an index file for … [See Man Page]'
complete -c mplex -s r -l mux-bitrate --description 'The total (non VBR) / peak (VBR) bit-rate of th… [See Man Page]'
complete -c mplex -s b -l video-buffer --description 'A comma-seperateed list of video decoder buffer… [See Man Page]'
complete -c mplex -s L -l lpcm-params --description 'samples_per_sec:channels:bits_per_sample.'
complete -c mplex -s l -l mux-limit --description 'Multiplex limit.'
complete -c mplex -s O -l sync-offset --description 'Set the presentation timestamp offset of video stream w. r. t.'
complete -c mplex -s d -l subpicture-delay --description 'Specify offset of timestamps (video-subpicture)… [See Man Page]'
complete -c mplex -s R -l run-in --description 'Set a non-default run-in (the time data is prel… [See Man Page]'
complete -c mplex -s V -l vbr --description 'Force variable bit rate multiplexing even if se… [See Man Page]'
complete -c mplex -s C -o cbr --description 'Force constant bit rate multiplexing even if se… [See Man Page]'
complete -c mplex -s s -l sector-size --description 'This option specifies the sector size of the ou… [See Man Page]'
complete -c mplex -s p -l packets-per-pack --description 'This option specifies the number of packets per… [See Man Page]'
complete -c mplex -s S -l max-segment-size --description 'This option specifies the maximum size of outpu… [See Man Page]'
complete -c mplex -s M -l ignore-seqend-markers --description 'This flag makes mplex ignore sequence end marke… [See Man Page]'
complete -c mplex -s h -l system-headers --description 'A system header is generated in every pack rath… [See Man Page]'

