# mubusy
# Autogenerated from man page /usr/share/man/man1/mubusy.1.gz
# using Deroffing man parser
complete -c mubusy -s p --description 'Use the specified password if the file is encrypted.'
complete -c mubusy -s g --description 'Garbage collect objects that have no references… [See Man Page]'
complete -c mubusy -s d --description 'Decompress streams.'
complete -c mubusy -s b --description 'Print streams as binary data and omit the object header.'
complete -c mubusy -s e --description 'Print streams in their original encoded (or compressed) form.'

