# mudraw
# Autogenerated from man page /usr/share/man/man1/mudraw.1.gz
# using Deroffing man parser
complete -c mudraw -s o --description 'The image format is deduced from the output file name.'
complete -c mudraw -s p --description 'Use the specified password if the file is encrypted.'
complete -c mudraw -s r --description 'Render the page at the specified resolution.'
complete -c mudraw -s w --description 'Render the page at the specified width (or, if … [See Man Page]'
complete -c mudraw -s h --description 'Render the page at the specified height (or, if… [See Man Page]'
complete -c mudraw -s f --description '\'Fit\' exactly; ignore the aspect ratio when mat… [See Man Page]'
complete -c mudraw -s R --description 'Rotate clockwise by given number of degrees.'
complete -c mudraw -s a --description 'Save the alpha channel.'
complete -c mudraw -s g --description 'Render in grayscale.'
complete -c mudraw -s m --description 'Show timing information.'
complete -c mudraw -s 5 --description 'Print an MD5 checksum of the rendered image data for each page.'
complete -c mudraw -s t --description 'Print the text contents of each page in UTF-8 encoding.'
complete -c mudraw -s x --description 'Print the display list used to render each page.'
complete -c mudraw -s A --description 'Disable the use of accelerated functions.'
complete -c mudraw -s G --description 'Gamma correct the output image.  Some typical values are 0.'
complete -c mudraw -s I --description 'Invert the output image colors.'

