# mupdf
# Autogenerated from man page /usr/share/man/man1/mupdf.1.gz
# using Deroffing man parser
complete -c mupdf -s p --description 'Uses the given password to open an encrypted PDF file.'
complete -c mupdf -s r --description 'Changes the initial zoom level, specified as th… [See Man Page]'

