# musixtex
# Autogenerated from man page /usr/share/man/man1/musixtex.1.gz
# using Deroffing man parser
complete -c musixtex -s v --description 'output program name and version number, and quit.'
complete -c musixtex -s h --description 'output usage summary and quit.'
complete -c musixtex -s l --description 'changes the TeX processor to  latex (1) or  pdflatex (1).'
complete -c musixtex -s p --description 'changes the TeX processor to   pdfetex (1)  or … [See Man Page]'
complete -c musixtex -s d --description 'changes the dvi processor to  dvipdfm (1).'
complete -c musixtex -s s --description 'stops processing at the dvi file.'
complete -c musixtex -s f --description 'default processing.'

