# mwm
# Autogenerated from man page /usr/share/man/man1/mwm.1.gz
# using Deroffing man parser
complete -c mwm -o xrm --description 'Set resource.'
complete -c mwm -o display --description 'Specifies display to be used.'
complete -c mwm -o debug --description 'Enable debugging.'
complete -c mwm -o multiscreen --description 'Use multiple screens.'
complete -c mwm -o name --description 'Make mwm retrieve its resources using the given name.'
complete -c mwm -o screens --description 'Manage multiple screens.    Not yet supported.'
complete -c mwm -o version --description 'Print version information to stderr.'

