# nice
# Autogenerated from man page /usr/share/man/man1/nice.1p.gz
# using Deroffing man parser
complete -c nice -s x --description 'the command nice --1 utility.'
complete -c nice -s 0 --description 'message and does not run the utility.'

