# nsdejavu
# Autogenerated from man page /usr/share/man/man1/nsdejavu.1.gz
# using Deroffing man parser
complete -c nsdejavu -o netscape --description 'The plugin first searches a program named djview .'

