# ntpsnmpd
# Autogenerated from man page /usr/share/man/man1/ntpsnmpd.1.gz
# using Deroffing man parser
complete -c ntpsnmpd -s n -l nofork --description 'Do not fork. sp.'
complete -c ntpsnmpd -s p -l syslog --description 'Log to syslog(). sp.'
complete -c ntpsnmpd -l agentxsocket --description 'The socket address ntpsnmpd uses to connect to net-snmpd.'
complete -c ntpsnmpd -s '?' -l help --description 'Display extended usage information and exit.'
complete -c ntpsnmpd -s '!' -l more-help --description 'Extended usage information passed thru pager.'
complete -c ntpsnmpd -s '>' -l save-opts --description 'Save the option state to rcfile.'
complete -c ntpsnmpd -s '<' -l load-opts -l no-load-opts --description 'Load options from rcfile.'
complete -c ntpsnmpd -l version --description 'Output version of program and exit.'

