# octave-config
# Autogenerated from man page /usr/share/man/man1/octave-config.1.gz
# using Deroffing man parser
complete -c octave-config -l m-site-dir --description 'Display the main directory for local, or site-specific, .'
complete -c octave-config -l oct-site-dir --description 'Display the main directory for local, or site-specific, .'
complete -c octave-config -s p -l print --description 'Print the default value of the Octave configura… [See Man Page]'
complete -c octave-config -s v -l version --description 'Display the version number of   octave (1).'
complete -c octave-config -s h -s '?' -l help --description 'Print help message.  AUTHOR John W.  Eaton <jwe@octave. org>.'

