# ofxdump
# Autogenerated from man page /usr/share/man/man1/ofxdump.1.gz
# using Deroffing man parser
complete -c ofxdump -s h -l help --description 'Print help and exit.'
complete -c ofxdump -s V -l version --description 'Print version and exit.'
complete -c ofxdump -s f -l import-format --description 'Force the file format of the file(s) specified … [See Man Page]'
complete -c ofxdump -l list-import-formats --description 'List available import file formats \'import-format\' command.'
complete -c ofxdump -l msg_parser --description 'Output file parsing messages  (default=off).'
complete -c ofxdump -l msg_debug --description 'Output messages meant for debuging  (default=off).'
complete -c ofxdump -l msg_warning --description 'Output warning messages about abnormal conditio… [See Man Page]'
complete -c ofxdump -l msg_error --description 'Output error messages  (default=on).'
complete -c ofxdump -l msg_info --description 'Output informational messages about the progres… [See Man Page]'
complete -c ofxdump -l msg_status --description 'Output status messages  (default=on).'

