# ompi_info
# Autogenerated from man page /usr/share/man/man1/ompi_info.1.gz
# using Deroffing man parser
complete -c ompi_info -s a -l all --description 'Show all configuration options and MCA parameters.'
complete -c ompi_info -l arch --description 'Show architecture Open MPI was compiled on.'
complete -c ompi_info -s c -l config --description 'Show configuration options.'
complete -c ompi_info -o gmca -l gmca --description 'Pass global MCA parameters that are applicable to all contexts.'
complete -c ompi_info -s h -l help --description 'Shows help / usage message.'
complete -c ompi_info -l hostname --description 'Show the hostname that Open MPI was configured and built on.'
complete -c ompi_info -l internal --description 'Show internal MCA parameters (not meant to be m… [See Man Page]'
complete -c ompi_info -o mca -l mca --description 'Pass context-specific MCA parameters; they are … [See Man Page]'
complete -c ompi_info -l param --description 'Show MCA parameters.'
complete -c ompi_info -l parsable --description 'When used in conjunction with other parameters,… [See Man Page]'
complete -c ompi_info -l path --description 'Show paths that Open MPI was configured with.'
complete -c ompi_info -l pretty --description 'When used in conjunction with other parameters,… [See Man Page]'
complete -c ompi_info -l parseable --description 'Synonym for --parsable.'
complete -c ompi_info -s v -l version --description 'Show version of Open MPI or a component.'

