# opt
# Autogenerated from man page /usr/share/man/man1/opt.1.gz
# using Deroffing man parser
complete -c opt -s f --description 'Enable binary output on terminals.'
complete -c opt -o help --description 'Print a summary of command line options.'
complete -c opt -s o --description 'Specify the output filename.'
complete -c opt -s S --description 'Write output in LLVM intermediate language (ins… [See Man Page]'
complete -c opt -o '{passname}' --description 'opt provides the ability to run any of LLVM\'s o… [See Man Page]'
complete -c opt -o std-compile-opts --description 'This is short hand for a standard list of compi… [See Man Page]'
complete -c opt -o disable-inlining --description 'This option is only meaningful when -std-compile-opts is given.'
complete -c opt -o disable-opt --description 'This option is only meaningful when -std-compile-opts is given.'
complete -c opt -o verify -o lower-setjmp -o 'funcresolve.' --description '.'
complete -c opt -o strip-debug --description 'This option causes opt to strip debug informati… [See Man Page]'
complete -c opt -o verify-each --description 'This option causes opt to add a verify pass aft… [See Man Page]'
complete -c opt -o profile-info-file --description 'Specify the name of the file loaded by the -pro… [See Man Page]'
complete -c opt -o stats --description 'Print statistics.'
complete -c opt -o time-passes --description 'Record the amount of time needed for each pass … [See Man Page]'
complete -c opt -o debug --description 'If this is a debug build, this option will enab… [See Man Page]'
complete -c opt -o load --description 'Load the dynamic object plugin.'
complete -c opt -s p --description 'Print module after each transformation.  EXIT STATUS.'

