# parcellite
# Autogenerated from man page /usr/share/man/man1/parcellite.1.gz
# using Deroffing man parser
complete -c parcellite -s '?' -l help --description 'Show help options.'
complete -c parcellite -s d -l daemon --description 'Run as daemon.'
complete -c parcellite -s n -l no-icon --description 'Do not use status icon.'
complete -c parcellite -s c -l clipboard --description 'Print clipboard contents.'
complete -c parcellite -s p -l primary --description 'Print primary contents ACTIONS Parcellite\'s act… [See Man Page]'

