# passwd
# Autogenerated from man page /usr/share/man/man1/passwd.1.gz
# using Deroffing man parser
complete -c passwd -s a -l all --description 'This option can be used only with -S and causes… [See Man Page]'
complete -c passwd -s d -l delete --description 'Delete a user\\*(Aqs password (make it empty).'
complete -c passwd -s e -l expire --description 'Immediately expire an account\\*(Aqs password.'
complete -c passwd -s h -l help --description 'Display help message and exit.'
complete -c passwd -s i -l inactive --description 'This option is used to disable an account after… [See Man Page]'
complete -c passwd -s k -l keep-tokens --description 'Indicate password change should be performed on… [See Man Page]'
complete -c passwd -s l -l lock --description 'Lock the password of the named account.'
complete -c passwd -s n -l mindays --description 'Set the minimum number of days between password… [See Man Page]'
complete -c passwd -s q -l quiet --description 'Quiet mode.'
complete -c passwd -s r -l repository --description 'change password in REPOSITORY repository.'
complete -c passwd -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c passwd -s S -l status --description 'Display account status information.'
complete -c passwd -s u -l unlock --description 'Unlock the password of the named account.'
complete -c passwd -s w -l warndays --description 'Set the number of days of warning before a pass… [See Man Page]'
complete -c passwd -s x -l maxdays --description 'Set the maximum number of days a password remains valid.'

