# pdbtool
# Autogenerated from man page /usr/share/man/man1/pdbtool.1.gz
# using Deroffing man parser
complete -c pdbtool -l pdb -s p --description '.'
complete -c pdbtool -l program -s P --description '.'
complete -c pdbtool -l program-tree -s T --description '.'
complete -c pdbtool -l color-out -s c --description '.'
complete -c pdbtool -l debug-csv -s C --description '.'
complete -c pdbtool -l debug-pattern --description 'option as comma-separated values.'
complete -c pdbtool -s D --description '.'
complete -c pdbtool -l file -s f --description '.'
complete -c pdbtool -l filter -s F --description '.'
complete -c pdbtool -l message -s M --description '.'
complete -c pdbtool -l template --description '.'
complete -c pdbtool -l directory --description '.'
complete -c pdbtool -l glob -s G --description '.'
complete -c pdbtool -l recursive -s r --description '.'
complete -c pdbtool -s '.' --description '.'
complete -c pdbtool -l iterate-outliers -s o --description '.'
complete -c pdbtool -l named-parsers -s n --description '.'
complete -c pdbtool -l samples --description '.'
complete -c pdbtool -l support -s S --description '.'
complete -c pdbtool -l validate --description '.'

