# plasmapkg
# Autogenerated from man page /usr/share/man/man1/plasmapkg.1.gz
# using Deroffing man parser
complete -c plasmapkg -s g -l global --description 'For install or remove, operates on packages ins… [See Man Page]'
complete -c plasmapkg -s t -l type --description 'The type of package, e. g.'
complete -c plasmapkg -s i -l install --description 'Install the package at \\(lqpath\\(rq.'
complete -c plasmapkg -s u -l upgrade --description 'Upgrade the package at \\(lqpath\\(rq.'
complete -c plasmapkg -s l -l list --description 'List installed packages.'
complete -c plasmapkg -s r -l remove --description 'Remove the package named \\(lqname\\(rq.'
complete -c plasmapkg -s p -l packageroot --description 'Absolute path to the package root.'

