# plasmoidviewer
# Autogenerated from man page /usr/share/man/man1/plasmoidviewer.1.gz
# using Deroffing man parser
complete -c plasmoidviewer -s c -l containment --description 'Name of the containment plugin [null].'
complete -c plasmoidviewer -s f -l formfactor --description 'The formfactor to use (horizontal, vertical, me… [See Man Page]'
complete -c plasmoidviewer -l list --description 'Displays a list of known applets.'
complete -c plasmoidviewer -l list-wallpapers --description 'Displays a list of known wallpapers.'
complete -c plasmoidviewer -l list-containments --description 'Displays a list of known containments.'
complete -c plasmoidviewer -s l -l location --description 'The location constraint to start the Containmen… [See Man Page]'
complete -c plasmoidviewer -s p -l pixmapcache --description 'The size in KB to set the pixmap cache to.'
complete -c plasmoidviewer -s s -l screenshot --description 'Takes a screenshot of the widget and saves it t… [See Man Page]'
complete -c plasmoidviewer -l screenshot-all --description 'Takes a screenshot of each widget and saves it … [See Man Page]'
complete -c plasmoidviewer -s t -l theme --description 'Desktop SVG theme to use.'
complete -c plasmoidviewer -s w -l wallpaper --description 'Name of the wallpaper plugin.'
complete -c plasmoidviewer -l list-remote --description 'List zeroconf announced remote widgets.'

