# pmx2pdf
# Autogenerated from man page /usr/share/man/man1/pmx2pdf.1.gz
# using Deroffing man parser
complete -c pmx2pdf -s v --description 'output program name and version number, and quit.'
complete -c pmx2pdf -s h --description 'output usage summary and quit.'
complete -c pmx2pdf -s l --description 'changes the TeX processor to  latex (1) or  pdflatex (1).'
complete -c pmx2pdf -s p --description 'changes the TeX processor to   pdfetex (1)  or … [See Man Page]'
complete -c pmx2pdf -s d --description 'changes the dvi processor to  dvipdfm (1).'
complete -c pmx2pdf -s s --description 'stops processing at the dvi file.'
complete -c pmx2pdf -s t --description 'stops processing at the tex (and midi) files.'
complete -c pmx2pdf -s i --description 'retain intermediate files.'
complete -c pmx2pdf -s f --description 'default processing.'

