# png2yuv
# Autogenerated from man page /usr/share/man/man1/png2yuv.1.gz
# using Type1
complete -c png2yuv -s b --description 'Frame offset:  skip output of the first \'num\' frames.'
complete -c png2yuv -s f --description 'Set the frame rate of stream accepts the same numbers.'
complete -c png2yuv -s I --description 'interlacing mode: p = none / progressive .'
complete -c png2yuv -s L --description '0 = non-interleaved (two successive fields per PNG file) .'
complete -c png2yuv -s l --description 'Specifies the number of loops (default: 0 loops ).'
complete -c png2yuv -s S --description 'chroma subsampling mode, only for professionals… [See Man Page]'
complete -c png2yuv -s n --description 'Specifies the nummber of frames to process.'
complete -c png2yuv -s j --description 'Read PNG frames with the name components as fol… [See Man Page]'

