# pnmtoy4m
# Autogenerated from man page /usr/share/man/man1/pnmtoy4m.1.gz
# using Type1
complete -c pnmtoy4m -s o --description 'Frame offset:  skip output of the first \'num\' frames.'
complete -c pnmtoy4m -s n --description 'Output a total of \'num\' output frames.'
complete -c pnmtoy4m -s B --description 'Interpret data as being  BGR rather than RGB.'
complete -c pnmtoy4m -s r --description 'Repeat last input frame until output is complete.'
complete -c pnmtoy4m -s D --description 'Treat each PNM image as a single (de-interleave… [See Man Page]'
complete -c pnmtoy4m -s F --description 'Set framerate encoded in output stream, as an e… [See Man Page]'
complete -c pnmtoy4m -s A --description 'Set pixel aspect ratio encoded in output stream… [See Man Page]'
complete -c pnmtoy4m -s I --description 'Set the output interlacing mode, encoded in the output stream.'

