# ppmtoy4m
# Autogenerated from man page /usr/share/man/man1/ppmtoy4m.1.gz
# using Type1
complete -c ppmtoy4m -s o --description 'Frame offset:  skip output of the first \'num\' frames.'
complete -c ppmtoy4m -s n --description 'Output a total of \'num\' output frames.'
complete -c ppmtoy4m -s F --description 'Set framerate encoded in output stream, as an e… [See Man Page]'
complete -c ppmtoy4m -s A --description 'Set pixel aspect ratio encoded in output stream… [See Man Page]'
complete -c ppmtoy4m -s B --description 'Interpret data as being BGR rather than RGB.'
complete -c ppmtoy4m -s I --description 'Set interlacing mode, used to interpret the PPM… [See Man Page]'
complete -c ppmtoy4m -s L --description 'For interlaced streams, treat each PPM image as… [See Man Page]'
complete -c ppmtoy4m -s r --description 'Repeat last input frame until output is complete.'
complete -c ppmtoy4m -s S --description 'Set chroma subsampling mode.'

