# pq2-ls-files-server
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-ls-files-server.1
# using Deroffing man parser
complete -c pq2-ls-files-server -s h -l help --description 'Display help information.'
complete -c pq2-ls-files-server -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-ls-files-server -s v --description 'Verbose mode.'
complete -c pq2-ls-files-server -s d -l dataset --description 'Alternative way to define the dataset to be analysed.'
complete -c pq2-ls-files-server -l server --description 'Alternative way to define the list of servers f… [See Man Page]'
complete -c pq2-ls-files-server -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-ls-files-server -s s --description 'Comma-separated list of servers for which the i… [See Man Page]'
complete -c pq2-ls-files-server -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

