# pq2-redistribute
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-redistribute.1
# using Deroffing man parser
complete -c pq2-redistribute -s h -l help --description 'Display help information.'
complete -c pq2-redistribute -l dryrun --description 'Only show the action that should be done (don\'t execute them).'
complete -c pq2-redistribute -s b --description 'Tag identifying the backend to be used.'
complete -c pq2-redistribute -s f --description 'File with the file movement directives produced… [See Man Page]'
complete -c pq2-redistribute -s r -l redir --description 'URL of the redirector from where the files shou… [See Man Page]'
complete -c pq2-redistribute -s t -l tmpdir --description 'Directory for temporary files; default is /tmp/<username>.'

