# pq2-put
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-put.1
# using Deroffing man parser
complete -c pq2-put -s h -l help --description 'Display help information.'
complete -c pq2-put -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-put -s v --description 'Verbose mode.'
complete -c pq2-put -s d -l dataset --description 'Alternative way to define path to the file with… [See Man Page]'
complete -c pq2-put -s o --description 'Options for registering datasets; a combination of: .'
complete -c pq2-put -l overwrite --description 'Alternative to \'-o O\'.'
complete -c pq2-put -l update --description 'Alternative to \'-o U\'.'
complete -c pq2-put -l trust --description 'Alternative to \'-o T\'.'
complete -c pq2-put -l tree --description 'Set the name of the default tree name to \'defau… [See Man Page]'
complete -c pq2-put -l staged --description 'Assume all files online or staged (option \'T\' or --trust only).'
complete -c pq2-put -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-put -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

