# pq2-ana-dist
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-ana-dist.1
# using Deroffing man parser
complete -c pq2-ana-dist -s h -l help --description 'Display help information.'
complete -c pq2-ana-dist -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-ana-dist -s v --description 'Verbose mode.'
complete -c pq2-ana-dist -l dataset --description 'Alternative way to define the datasets to be analysed.'
complete -c pq2-ana-dist -s s -l servers --description 'Comma-separated list of servers to be used (-s)… [See Man Page]'
complete -c pq2-ana-dist -s e -l exclude --description 'Comma-separated list of servers to be excluded … [See Man Page]'
complete -c pq2-ana-dist -s i -l ignore --description 'Comma-separated list of servers to be ignored i… [See Man Page]'
complete -c pq2-ana-dist -s m -l metrics --description 'Metrics to be used to calculate the degree of evenness: .'
complete -c pq2-ana-dist -s f -l filemv --description 'Defines the file where to save the result of th… [See Man Page]'
complete -c pq2-ana-dist -l 'plot[' --description 'Defines the file with the output plot with the … [See Man Page]'
complete -c pq2-ana-dist -l 'fout[' --description 'Defines the file where to save the output of th… [See Man Page]'
complete -c pq2-ana-dist -l 'fin[' --description 'Defines the ROOT file from where to fetch the o… [See Man Page]'
complete -c pq2-ana-dist -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-ana-dist -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

