# pq2-ls
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-ls.1
# using Deroffing man parser
complete -c pq2-ls -s h -l help --description 'Display help information.'
complete -c pq2-ls -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-ls -s v --description 'Verbose mode.'
complete -c pq2-ls -l forcescan --description 'Force opening of the datasets are open to get t… [See Man Page]'
complete -c pq2-ls -l noupdate --description 'In the case a cache is used, do not update the … [See Man Page]'
complete -c pq2-ls -l refresh --description 'Refresh the information (requires appropriate c… [See Man Page]'
complete -c pq2-ls -s d -l dataset --description 'Alternative way to define the dataset or the da… [See Man Page]'
complete -c pq2-ls -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-ls -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

