# pq2-info-server
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-info-server.1
# using Deroffing man parser
complete -c pq2-info-server -s h -l help --description 'Display help information.'
complete -c pq2-info-server -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-info-server -s v --description 'Verbose mode.'
complete -c pq2-info-server -l server --description 'Alternative way to define the server.'
complete -c pq2-info-server -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-info-server -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

