# pq2-rm
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-rm.1
# using Deroffing man parser
complete -c pq2-rm -s h -l help --description 'Display help information.'
complete -c pq2-rm -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-rm -s v --description 'Verbose mode.'
complete -c pq2-rm -s d -l dataset --description 'Alternative way to define the datasets to be removed.'
complete -c pq2-rm -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-rm -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

