# pq2-cache
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-cache.1
# using Deroffing man parser
complete -c pq2-cache -s h -l help --description 'Display help information.'
complete -c pq2-cache -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-cache -s v --description 'Verbose mode.'
complete -c pq2-cache -l dataset --description 'Alternative way to define the datasets to be removed.'
complete -c pq2-cache -s u -l url --description 'URL of the data server providing the informatio… [See Man Page]'
complete -c pq2-cache -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

