# pq2-verify
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2-verify.1
# using Deroffing man parser
complete -c pq2-verify -s h -l help --description 'Display help information.'
complete -c pq2-verify -s k -l keep --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2-verify -s v --description 'Verbose mode.'
complete -c pq2-verify -s d -l dataset --description 'Alternative way to define the datasets to be analyzed.'
complete -c pq2-verify -s o --description 'Options for veriying datasets.'
complete -c pq2-verify -l redir --description 'URL to be used to relocate the files.'
complete -c pq2-verify -s u -l url --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2-verify -s t -l tmpdir --description 'Directory for temporary files; defualt is /tmp/<username>.'

