# pq2
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/pq2.1
# using Deroffing man parser
complete -c pq2 -s d --description 'For all action but put, the dataset to be processed.'
complete -c pq2 -s u --description 'URL of the PROOF master or data server providin… [See Man Page]'
complete -c pq2 -s o --description 'Specify a string of options to be passed to the… [See Man Page]'
complete -c pq2 -s s --description 'Specify a server or a comma-separated list of s… [See Man Page]'
complete -c pq2 -s k --description 'Keep the temporary files created during the ana… [See Man Page]'
complete -c pq2 -s v --description 'Verbose mode OPTIONS for action verify The opti… [See Man Page]'
complete -c pq2 -s r --description 'Force re-location of the files via the specifie… [See Man Page]'
complete -c pq2 -s m --description 'Defines the metrics to be used in the distribution analysis.'
complete -c pq2 -s f --description 'Defines the file where to save the result of th… [See Man Page]'
complete -c pq2 -l outfile --description 'Defines the file where to save the output of th… [See Man Page]'
complete -c pq2 -l infile --description 'Defines the ROOT file from where to fetch the o… [See Man Page]'
complete -c pq2 -s i --description 'Specify a server or a comma-separated list of s… [See Man Page]'
complete -c pq2 -s e --description 'Specify a server or a comma-separated list of s… [See Man Page]'
complete -c pq2 -l plot --description 'Defines the file with the output plot with the … [See Man Page]'

