# pr
# Autogenerated from man page /usr/share/man/man1/pr.1p.gz
# using Deroffing man parser
complete -c pr -o column --description 'Produce multi-column output that is arranged in… [See Man Page]'
complete -c pr -o 'e[char][gap]' --description 'sp Expand each input <tab> to the next greater … [See Man Page]'
complete -c pr -o 'i[char][gap]' --description 'In output, replace multiple <space>s with <tab>… [See Man Page]'
complete -c pr -o 'n[char][width]' --description 'sp Provide width-digit line numbering (default … [See Man Page]'
complete -c pr -s p --description 'Pause before beginning each page if the standar… [See Man Page]'
complete -c pr -o 's[char]' --description 'Separate text columns by the single character c… [See Man Page]'
complete -c pr -s s --description 'its argument, and the options -e, -i, and.'
complete -c pr -s n --description 'from the option letter.'
complete -c pr -s e -s i --description 'Whether or not text columns are produced with i… [See Man Page]'
complete -c pr -s 2 --description 'a problem when a full page with headers and tra… [See Man Page]'

