# prepmx
# Autogenerated from man page /usr/share/man/man1/prepmx.1.gz
# using Deroffing man parser
complete -c prepmx -s b --description 'never unbeam eighth notes and shorter.'
complete -c prepmx -s c --description 'main music lines only - ignore chords.'
complete -c prepmx -s D --description 'enable debug mode.'
complete -c prepmx -s f --description 'use tonic sol-fa note names.'
complete -c prepmx -s i --description 'ignore errors.'
complete -c prepmx -s m --description 'music only - ignore lyrics.'
complete -c prepmx -s n --description 'indent first system and print default instrument names.'
complete -c prepmx -s t --description 'ignore uptext lines.'
complete -c prepmx -s u --description 'uptext synchronizes with notes only, not rests.'
complete -c prepmx -s v --description 'verbose progress report.'
complete -c prepmx -s w --description 'enable pedantic warnings.'

