# prs
# Autogenerated from man page /usr/share/man/man1/prs.1p.gz
# using Deroffing man parser
complete -c prs -s d --description 'Specify the output data specification.'
complete -c prs -o 'r[SID]' --description 'Specify the SCCS identification string (SID) of… [See Man Page]'
complete -c prs -s e --description 'Request information for all deltas created earl… [See Man Page]'
complete -c prs -s l --description 'Request information for all deltas created late… [See Man Page]'
complete -c prs -s c --description 'Indicate the cutoff date-time, in the form:  . sp . RS .'
complete -c prs -s a --description 'Request writing of information for both removed… [See Man Page]'

