# ps
# Autogenerated from man page /usr/share/man/man1/ps.1p.gz
# using Deroffing man parser
complete -c ps -o 'A.)' --description '.'
complete -c ps -o 'e.' --description 'compromise was selected.'

