# purifyeps
# Autogenerated from man page /usr/share/man/man1/purifyeps.1.gz
# using Type1
complete -c purifyeps -l help --description 'Display \\*(L"Usage\\*(R" and \\*(L"Options\\*(R" f… [See Man Page]'
complete -c purifyeps -s V -l version --description 'Display the purifyeps version number, copyright, and license.'
complete -c purifyeps -l fontmap --description 'Specify the name of a file that tells purifyeps… [See Man Page]'
complete -c purifyeps -l make-man --description 'Automatically create a Unix man page for purifyeps.'

