# pycolor2
# Autogenerated from man page /usr/share/man/man1/pycolor2.1.gz
# using Deroffing man parser
complete -c pycolor2 -s h -l help --description 'Output a brief help message.'
complete -c pycolor2 -s s -l scheme --description 'Give the color scheme to use.'

