# pydf
# Autogenerated from man page /usr/share/man/man1/pydf.1.gz
# using Deroffing man parser
complete -c pydf -l help --description 'Show summary of options.'
complete -c pydf -s v -l version --description 'Show version of program.'
complete -c pydf -s a -l all --description 'include filesystems having 0 blocks.'
complete -c pydf -s h -l human-readable --description 'print sizes in human readable format (e. g.'
complete -c pydf -s H -l si --description 'likewise, but use powers of 1000 not 1024.'
complete -c pydf -l block-size --description 'use SIZE-byte blocks.'
complete -c pydf -s k -l kilobytes --description 'like --block-size=1024.'
complete -c pydf -s i -l inodes --description 'show information about inodes instead of blocks.'
complete -c pydf -s l -l local --description 'limit listing to local filesystems.'
complete -c pydf -s m -l megabytes --description 'like --block-size=1048576.'
complete -c pydf -s g -l gigabytes --description 'like --block-size=1073741824.'
complete -c pydf -l blocks --description 'use filesystem native block size.'
complete -c pydf -l bw --description 'do not use colours.'
complete -c pydf -l mounts --description 'file to get mount information from.'
complete -c pydf -s B -l show-binds --description 'Show also mount --bind mounted filesystems.'

