# pyreverse
# Autogenerated from man page /usr/share/man/man1/pyreverse.1.gz
# using Deroffing man parser
complete -c pyreverse -s h -l help --description 'show help message and exit.'
complete -c pyreverse -o 'p<name>' -l project --description 'set project name to <name> if not using -c option.'
complete -c pyreverse -o 'i<file>' -l ignore --description 'add <file> (may be a directory) to the black list (not parsed).'
complete -c pyreverse -o 'f<mode>' -l filter-mode --description 'filter attributes and functions according to <mode>.'
complete -c pyreverse -o 'd<file>' -l diadefs --description 'create diagram according to the diagrams definitions in <file>.'
complete -c pyreverse -s c -l class --description 'create a class diagram with all classes related… [See Man Page]'
complete -c pyreverse -s a -l show-ancestors --description 'show <ancestor> generations of ancestor classes… [See Man Page]'
complete -c pyreverse -s A -l all-ancestors --description 'show all ancestors off all classes in <projects… [See Man Page]'
complete -c pyreverse -s s -l show-associated --description 'show <ass_level> associated classes.'
complete -c pyreverse -s S -l all-associated --description 'show recursively all associated off all associa… [See Man Page]'
complete -c pyreverse -s b -l builtin --description 'include builtin objects in representation of cl… [See Man Page]'
complete -c pyreverse -s m -l module-names --description 'include module name in representation of classes.'
complete -c pyreverse -s k -l only-classnames --description 'don\'t show attributes and methods in the class … [See Man Page]'
complete -c pyreverse -s o -l output --description 'create a *. <format> output file if format available.'
complete -c pyreverse -o a1 -o s1 --description 'diagram  of the <project> modules, while -m wil… [See Man Page]'

