# qalter
# Autogenerated from man page /usr/share/man/man1/qalter.1p.gz
# using Deroffing man parser
complete -c qalter -s a --description 'Redefine the time at which the batch job become… [See Man Page]'
complete -c qalter -s A --description 'sp Redefine the account to which the resource c… [See Man Page]'
complete -c qalter -s c --description 'Redefine whether the batch job should be checkp… [See Man Page]'
complete -c qalter -s e --description 'Redefine the path to be used for the standard e… [See Man Page]'
complete -c qalter -s h --description 'Redefine the types of holds, if any, on the batch job.'
complete -c qalter -s j --description 'Redefine which streams of the batch job are to be merged.'
complete -c qalter -s k --description 'Redefine which output of the batch job to retai… [See Man Page]'
complete -c qalter -s l --description 'sp Redefine the resources that are allowed or r… [See Man Page]'
complete -c qalter -s m --description 'sp Redefine the points in the execution of the … [See Man Page]'
complete -c qalter -s M --description 'Redefine the list of users to which the batch s… [See Man Page]'
complete -c qalter -s N --description 'Redefine the name of the batch job.'
complete -c qalter -s o --description 'Redefine the path for the standard output of the batch job.'
complete -c qalter -s p --description 'Redefine the priority of the batch job.'
complete -c qalter -s r --description 'Redefine whether the batch job is rerunnable.'
complete -c qalter -s S --description 'sp Redefine the shell that interprets the scrip… [See Man Page]'
complete -c qalter -s u --description 'Redefine the user name under which the batch jo… [See Man Page]'
complete -c qalter -s v -o 'q.' -s V --description '.'

