# qselect
# Autogenerated from man page /usr/share/man/man1/qselect.1p.gz
# using Deroffing man parser
complete -c qselect -o 'a[op]date_time' --description 'sp Restrict selection to a specific time, or a range of times.'
complete -c qselect -s A --description 'sp Restrict selection to the batch jobs chargin… [See Man Page]'
complete -c qselect -o 'c[op]interval' --description 'sp Restrict selection to batch jobs within a ra… [See Man Page]'
complete -c qselect -s h --description 'Restrict selection to batch jobs that have a sp… [See Man Page]'
complete -c qselect -s l --description 'sp Restrict selection to batch jobs with specif… [See Man Page]'
complete -c qselect -s N --description 'Restrict selection to batch jobs with a specified name.'
complete -c qselect -o 'p[op]priority' --description 'sp Restrict selection to batch jobs of the spec… [See Man Page]'
complete -c qselect -s q --description 'sp Restrict selection to the specified batch qu… [See Man Page]'
complete -c qselect -s r --description 'Restrict selection to batch jobs with the speci… [See Man Page]'
complete -c qselect -s s --description 'Restrict selection to batch jobs in the specified states.'
complete -c qselect -s a --description '.'
complete -c qselect -s c --description '.'
complete -c qselect -s p --description '.'
complete -c qselect -s u --description 'Restrict selection to batch jobs owned by the s… [See Man Page]'

