# rcp
# Autogenerated from man page /usr/share/man/man1/rcp.1.gz
# using Deroffing man parser
complete -c rcp -s d -l target-directory --description 'copy all SOURCE arguments into DIRECTORY.'
complete -c rcp -s f -l from --description 'copying from remote host.'
complete -c rcp -s p -l preserve --description 'attempt to preserve (duplicate) in its copies t… [See Man Page]'
complete -c rcp -s r -l recursive --description 'if any of the source files are directories, cop… [See Man Page]'
complete -c rcp -s t -l to --description 'copying to remote host.'
complete -c rcp -s '?' -l help --description 'give this help list.'
complete -c rcp -l usage --description 'give a short usage message.'
complete -c rcp -s V -l version --description 'print program version.'

