# readpst
# Autogenerated from man page /usr/share/man/man1/readpst.1.gz
# using Deroffing man parser
complete -c readpst -s D --description 'Include deleted items in the output.'
complete -c readpst -s M --description 'Output messages in MH (rfc822) format as separate files.'
complete -c readpst -s S --description 'Output messages into separate files.'
complete -c readpst -s V --description 'Show program version and exit.'
complete -c readpst -s b --description 'Do not save the attachments for the RTF format … [See Man Page]'
complete -c readpst -s c --description 'Set the Contact output mode.'
complete -c readpst -s d --description 'Specify name of debug log file.'
complete -c readpst -s e --description 'Same as the M option, but each output file will… [See Man Page]'
complete -c readpst -s h --description 'Show summary of options and exit.'
complete -c readpst -s j --description 'Specifies the maximum number of parallel jobs.'
complete -c readpst -s k --description 'Changes the output format to KMail.'
complete -c readpst -s o --description 'Specifies the output directory.'
complete -c readpst -s q --description 'Changes to silent mode.'
complete -c readpst -s r --description 'Changes the output format to Recursive.'
complete -c readpst -s t --description 'Specifies the item types that are processed.'
complete -c readpst -s u --description 'Sets Thunderbird mode, a submode of recursive mode.'
complete -c readpst -s w --description 'Overwrite any previous output files.'

