# rev
# Autogenerated from man page /usr/share/man/man1/rev.1.gz
# using Deroffing man parser
complete -c rev -s V -l version --description 'Output version information and exit.'
complete -c rev -s h -l help --description 'Output help and exit.'

