# rlibmap
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/rlibmap.1
# using Deroffing man parser
complete -c rlibmap -l help --description 'Gives a short list of options avaliable, and exit.'
complete -c rlibmap -s f --description 'What!?.'
complete -c rlibmap -s r --description 'Read map file mapfile.'
complete -c rlibmap -s o --description 'Output on mapfile.'
complete -c rlibmap -s l --description 'Library to inspect.'
complete -c rlibmap -s d --description 'Dependency library.'
complete -c rlibmap -s c --description 'Specify CINT linkdef to use SEE ALSO root(1), rootcint(1).'

