# rmdel
# Autogenerated from man page /usr/share/man/man1/rmdel.1p.gz
# using Deroffing man parser
complete -c rmdel -s r --description 'Specify the SCCS identification string ( SID) o… [See Man Page]'

