# rmkdepend
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/rmkdepend.1
# using Deroffing man parser
complete -c rmkdepend -o Dname -o Dname --description 'Define.'
complete -c rmkdepend -o Iincludedir --description 'Include directory.'
complete -c rmkdepend -o Yincludedir --description 'Replace all of the standard include directories… [See Man Page]'
complete -c rmkdepend -s a --description 'Append the dependencies to the end of the file … [See Man Page]'
complete -c rmkdepend -o fmakefile --description 'Filename.'
complete -c rmkdepend -o oobjsuffix --description 'Object file suffix.'
complete -c rmkdepend -o pobjprefix --description 'Object file prefix.'
complete -c rmkdepend -o sstring --description 'Starting string delimiter.'
complete -c rmkdepend -o wwidth --description 'Line width.'
complete -c rmkdepend -s v --description 'Verbose operation.'
complete -c rmkdepend -s m --description 'Warn about multiple inclusion.'
complete -c rmkdepend -s f --description 'option.  It first searches the makefile for the line.'
complete -c rmkdepend -s s --description 'option, as a delimiter for the dependency output.'
complete -c rmkdepend -o 'o.b' --description 'or ``:obj\'\' with.'
complete -c rmkdepend -o o:obj --description 'and so forth.'
complete -c rmkdepend -o ttargetfilename --description 'Filename.'
complete -c rmkdepend -s I --description 'and.'
complete -c rmkdepend -s D --description 'options; and that most files in a single direct… [See Man Page]'

