# roota
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/roota.1
# using Deroffing man parser
complete -c roota -s b --description 'Run in batch mode without graphics.'
complete -c roota -s n --description 'Do not execute logon and logoff macros as specified in   .'
complete -c roota -s q --description 'Exit after processing command line macro files.'
complete -c roota -s '?' --description 'Show summary of options.'
complete -c roota -s l --description 'Do not show splash screen SEE ALSO.'

