# root-config
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/root-config.1
# using Deroffing man parser
complete -c root-config -l help --description 'Gives a short list of options avaliable, and exit.'
complete -c root-config -l version --description 'Report the version number of installed ROOT, and exit.'
complete -c root-config -l prefix --description 'If no arguments is given, reports where ROOT is installed.'
complete -c root-config -l exec-prefix --description 'If no argument is given, report where the libra… [See Man Page]'
complete -c root-config -l libdir --description 'Print the directory where the ROOT libraries are installed.'
complete -c root-config -l incdir --description 'Print the directory where the ROOT headers are installed.'
complete -c root-config -l libs --description 'Output a line suitable for linking a program ag… [See Man Page]'
complete -c root-config -l glibs --description 'As above, but also output for the graphics libraries.'
complete -c root-config -l cflags --description 'Output a line suitable for compiling a source f… [See Man Page]'
complete -c root-config -l new --description 'Put the libNew. so library in the library lists.'
complete -c root-config -l nonew --description 'Compatiblity option.  Does nothing.'
complete -c root-config -l auxlibs --description 'Print auxiliary libraries and/or system linker flags.'
complete -c root-config -l noauxlibs --description 'Do not print auxiliary libraries and/or system … [See Man Page]'
complete -c root-config -l noauxcflags --description 'Do not print auxiliary compiler flags in the ou… [See Man Page]'
complete -c root-config -l auxcflags --description 'Print auxiliary compiler flags.'
complete -c root-config -l 'cflags.' --description '.'
complete -c root-config -l noldflags --description 'Do not print library path link option in output of --libs and.'
complete -c root-config -l 'glibs.' --description 'SEE ALSO root(1), root-cint(1).'

