# rootcint
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/rootcint.1
# using Deroffing man parser
complete -c rootcint -s c --description 'also the interpreter method interface stubs wil… [See Man Page]'
complete -c rootcint -s f --description 'option to overwite the output file.'
complete -c rootcint -o 'I$../include' -o DDebug --description 'The (optional) file  LinkDef. h  looks like:  #ifdef __CINT__.'

