# rootd
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/rootd.1
# using Deroffing man parser
complete -c rootd -s '?' --description '\\" Show summary of options.'
complete -c rootd -s b --description 'specifies the tcp window size in bytes (e. g.  see http://www.'
complete -c rootd -s d --description 'level of debug info written to syslogd 0 = no d… [See Man Page]'
complete -c rootd -s D --description 'read access rules from file <rootdaemonrc>.'
complete -c rootd -s f --description 'run in the foreground (output on the window); u… [See Man Page]'
complete -c rootd -s i --description 'indicates that rootd was started by inetd(8) or xinetd(8).'
complete -c rootd -o noauth --description 'do not require client authentication.'
complete -c rootd -s p --description 'specifies the port number to listen on.'
complete -c rootd -s r --description 'files can only be opened in read-only mode.'
complete -c rootd -s s --description 'specifies the port number for the sshd daemon u… [See Man Page]'
complete -c rootd -s T --description 'specifies the directory path to be used to plac… [See Man Page]'
complete -c rootd -s w --description 'do not check /etc/hosts. equiv, $HOME/.'

