# sccs
# Autogenerated from man page /usr/share/man/man1/sccs.1p.gz
# using Deroffing man parser
complete -c sccs -s d --description 'A pathname of a directory to be used as a root … [See Man Page]'
complete -c sccs -s p --description 'A pathname of a directory in which the SCCS files are located.'
complete -c sccs -s r --description 'Invoke command with the real user ID of the pro… [See Man Page]'
complete -c sccs -s k -s l -s s --description 'and -x options shall be passed to get.'
complete -c sccs -s e --description '.'
complete -c sccs -s h -s b --description 'passed to diff.  A -C option shall be passed to diff as -c.'
complete -c sccs -s U --description '.'

