# set
# Autogenerated from man page /usr/share/man/man1/set.1p.gz
# using Deroffing man parser
complete -c set -s a --description 'When this option is on, the export attribute sh… [See Man Page]'
complete -c set -s b --description 'This option shall be supported if the implement… [See Man Page]'
complete -c set -s C --description '(Uppercase C.'
complete -c set -s e --description 'When this option is on, if a simple command fai… [See Man Page]'
complete -c set -s f --description 'The shell shall disable pathname expansion.'
complete -c set -s h --description 'Locate and remember utilities invoked by functi… [See Man Page]'
complete -c set -s m --description 'This option shall be supported if the implement… [See Man Page]'
complete -c set -s n --description 'The shell shall read commands but does not exec… [See Man Page]'
complete -c set -s o --description 'Write the current settings of the options to st… [See Man Page]'
complete -c set -s u --description 'The shell shall write a message to standard err… [See Man Page]'
complete -c set -s v --description 'The shell shall write its input to standard err… [See Man Page]'
complete -c set -s x --description 'The shell shall write to standard error a trace… [See Man Page]'
complete -c set -s k --description 'The -k flag was originally added by the author … [See Man Page]'
complete -c set -s t --description 'The -t flag is hard to specify and almost never used.'
complete -c set -o able --description 'the historical practice of using + option was s… [See Man Page]'

