# sh
# Autogenerated from man page /usr/share/man/man1/sh.1p.gz
# using Deroffing man parser
complete -c sh -s c --description 'Read commands from the command_string operand.'
complete -c sh -s i --description 'Specify that the shell is interactive; see below.'
complete -c sh -s o -s u -s v --description 'and -x options are described as part of the set… [See Man Page]'
complete -c sh -s s --description 'Read commands from the standard input.'

