# spec2arch
# Autogenerated from man page /usr/share/man/man1/spec2arch.1.gz
# using Deroffing man parser
complete -c spec2arch -s b --description 'Don\'t apply corrections to the build() block.'
complete -c spec2arch -s e --description 'Do not invoke the editor with the PKGBUILD file… [See Man Page]'
complete -c spec2arch -s n --description 'Don\'t check the generated PKGBUILD file with namcap.'
complete -c spec2arch -s o --description 'Don\'t overwrite target if exists (overwrites co… [See Man Page]'
complete -c spec2arch -s w --description 'Do not put the warning in the PKGBUILD file (ov… [See Man Page]'
complete -c spec2arch -l baseurl --description 'Set SRC_BASEURL to <baseurl> (overwrites config… [See Man Page]'
complete -c spec2arch -l editor --description 'Define the editor to use to edit the created PK… [See Man Page]'
complete -c spec2arch -l md5of --description 'Calculate md5sums of the given file(s).'

