# ssh2rpd
# Autogenerated from man page /data/work/cern/root5.34.03/man/man1/ssh2rpd.1
# using Deroffing man parser
complete -c ssh2rpd -l help --description 'Gives a short list of options avaliable, and ex… [See Man Page]'

