# subtitleeditor
# Autogenerated from man page /usr/share/man/man1/subtitleeditor.1.gz
# using Deroffing man parser
complete -c subtitleeditor -s '?' -l help --description '.'
complete -c subtitleeditor -l help-all --description '.'
complete -c subtitleeditor -l help-gst --description '.'
complete -c subtitleeditor -l help-gtk --description '.'
complete -c subtitleeditor -s p -l profile --description '.'
complete -c subtitleeditor -s e -l encoding --description '.'
complete -c subtitleeditor -s v -l video --description '.'
complete -c subtitleeditor -s w -l waveform --description '.'

