# syslog-ng-ctl
# Autogenerated from man page /usr/share/man/man1/syslog-ng-ctl.1.gz
# using Deroffing man parser
complete -c syslog-ng-ctl -l stderr --description 'or.'
complete -c syslog-ng-ctl -s e --description 'option, the messages will be sent to stderr.'
complete -c syslog-ng-ctl -l control -s c --description '.'

