# systemd-coredumpctl
# Autogenerated from man page /usr/share/man/man1/systemd-coredumpctl.1.gz
# using Deroffing man parser
complete -c systemd-coredumpctl -l help -s h --description 'Print a short help text and exit.'
complete -c systemd-coredumpctl -l version --description 'Print a short version string and exit.'
complete -c systemd-coredumpctl -l field -s F --description 'Print all possible data values the specified fi… [See Man Page]'
complete -c systemd-coredumpctl -l output -s o --description 'Write the core to FILE.'
complete -c systemd-coredumpctl -l no-pager --description 'Do not pipe output of list into a pager.'
complete -c systemd-coredumpctl -l no-legend --description 'Do not print the column headers.'
complete -c systemd-coredumpctl -o 'o/--output.' --description 'gdb.'

