# systemd-delta
# Autogenerated from man page /usr/share/man/man1/systemd-delta.1.gz
# using Deroffing man parser
complete -c systemd-delta -s h -l help --description 'Prints a short help text and exits.'
complete -c systemd-delta -l version --description 'Prints a short version string and exits.'
complete -c systemd-delta -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-delta -l diff --description 'When showing modified files, when a file is ove… [See Man Page]'
complete -c systemd-delta -l type -s t --description '.'

