# systemd-nspawn
# Autogenerated from man page /usr/share/man/man1/systemd-nspawn.1.gz
# using Deroffing man parser
complete -c systemd-nspawn -l help -s h --description 'Prints a short help text and exits.'
complete -c systemd-nspawn -l directory -s D --description 'Directory to use as file system root for the na… [See Man Page]'
complete -c systemd-nspawn -l boot -s b --description 'Automatically search for an init binary and inv… [See Man Page]'
complete -c systemd-nspawn -l user -s u --description 'Run the command under specified user, create ho… [See Man Page]'
complete -c systemd-nspawn -l uuid --description 'Set the specified uuid for the container.'
complete -c systemd-nspawn -l controllers -s C --description 'Makes the container appear in other hierarchies… [See Man Page]'
complete -c systemd-nspawn -l private-network --description 'Turn off networking in the container.'
complete -c systemd-nspawn -l read-only --description 'Mount the root file system read only for the container.'
complete -c systemd-nspawn -l capability --description 'List one or more additional capabilities to gra… [See Man Page]'
complete -c systemd-nspawn -l link-journal --description 'Control whether the container\\*(Aqs journal sha… [See Man Page]'
complete -c systemd-nspawn -s j --description 'Equivalent to --link-journal=guest.'

