# systemd-cgls
# Autogenerated from man page /usr/share/man/man1/systemd-cgls.1.gz
# using Deroffing man parser
complete -c systemd-cgls -s h -l help --description 'Prints a short help text and exits.'
complete -c systemd-cgls -l version --description 'Prints a short version string and exits.'
complete -c systemd-cgls -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-cgls -l all --description 'Don\\*(Aqt hide empty control groups in the output.'
complete -c systemd-cgls -s k --description 'Include kernel threads in output.'

