# systemd-analyze
# Autogenerated from man page /usr/share/man/man1/systemd-analyze.1.gz
# using Deroffing man parser
complete -c systemd-analyze -s h -l help --description 'Prints a short help text and exits.'
complete -c systemd-analyze -l user --description 'Shows performance data of user sessions instead… [See Man Page]'

