# tccat
# Autogenerated from man page /usr/share/man/man1/tccat.1.gz
# using Deroffing man parser
complete -c tccat -s i --description 'Specify input source.   If ommited, stdin is assumed.'
complete -c tccat -s t --description 'Tell tccat about the type of input.'
complete -c tccat -s T --description 'Select DVD  title and extract only a single  ch… [See Man Page]'
complete -c tccat -s L --description 'This option tells tccat to loop through all cha… [See Man Page]'
complete -c tccat -s S --description 'Seek to program stream (VOB) offset nx2kB befor… [See Man Page]'
complete -c tccat -s P --description 'Stream full DVD title specified by -T.'
complete -c tccat -s a --description 'Use this option to dump an AVI-file/socket audio stream.'
complete -c tccat -s d --description 'With this option you can specify a bitmask to e… [See Man Page]'
complete -c tccat -s v --description 'Print version information and exit.'

