# tcdemux
# Autogenerated from man page /usr/share/man/man1/tcdemux.1.gz
# using Deroffing man parser
complete -c tcdemux -s i --description 'Specify input source.   If ommited, stdin is assumed. br.'
complete -c tcdemux -s x --description 'Process only packets containing given  codec as payload.'
complete -c tcdemux -s t --description 'Specify the input file type  magic.'
complete -c tcdemux -s a --description 'Process only packets containing given audio tra… [See Man Page]'
complete -c tcdemux -s s --description 'Select specific multimedia track using the stan… [See Man Page]'
complete -c tcdemux -s f --description 'Specify the frame rate  fps for subtitle meta i… [See Man Page]'
complete -c tcdemux -s S --description 'Select a program unit  unit and a selected GOP … [See Man Page]'
complete -c tcdemux -s O --description 'Do not skip initial sequence.  Used internally by transcode.'
complete -c tcdemux -s A --description 'Select packets using an identifier for extracti… [See Man Page]'
complete -c tcdemux -s M --description 'Select synchronization strategy  mode.'
complete -c tcdemux -s P --description 'Write GOP meta information to  file instead of \\fstdout. br.'
complete -c tcdemux -s W --description 'Print a navigation log file for a given video stream to stdout.'
complete -c tcdemux -s d --description 'With this option you can specify a bitmask to e… [See Man Page]'
complete -c tcdemux -s v --description 'Print version information and exit.'

