# tcdecode
# Autogenerated from man page /usr/share/man/man1/tcdecode.1.gz
# using Deroffing man parser
complete -c tcdecode -s i --description 'Specify input source.   If ommited, stdin is assumed.'
complete -c tcdecode -s g --description 'video frame width and height [720x576].'
complete -c tcdecode -s C --description 'decode and print out only this frame interval (… [See Man Page]'
complete -c tcdecode -s x --description 'source codec, if not detected of reading from stdin.'
complete -c tcdecode -s t --description 'Currently only argument supported is "lavc".'
complete -c tcdecode -s y --description 'target codec.'
complete -c tcdecode -s s --description 'audio gain for AC3 downmixing [1. 0,1. 0,1. 0].'
complete -c tcdecode -s Y --description 'decoded Digital Video (raw) YUV frame is in YUY… [See Man Page]'
complete -c tcdecode -s A --description 'audio flag for AC3/A52 decoder [none].'
complete -c tcdecode -s Q --description 'decoding quality.  Certain codecs, e. g.'
complete -c tcdecode -s d --description 'With this option you can specify a bitmask to e… [See Man Page]'
complete -c tcdecode -s v --description 'Print version information and exit.'

