# tcmodchain
# Autogenerated from man page /usr/share/man/man1/tcmodchain.1.gz
# using Deroffing man parser
complete -c tcmodchain -s m --description 'Look in Path instead of the compiled-in module … [See Man Page]'
complete -c tcmodchain -s C --description 'Enable check mode.'
complete -c tcmodchain -s L --description 'Enable list mode.'
complete -c tcmodchain -s d --description 'Specify the verbosiness level to use, like transcode does.'
complete -c tcmodchain -s v --description 'Print version information and exit.'

