# tcmodinfo
# Autogenerated from man page /usr/share/man/man1/tcmodinfo.1.gz
# using Deroffing man parser
complete -c tcmodinfo -s i --description 'Specify the name of the module.'
complete -c tcmodinfo -s m --description 'Look in Path instead of the compiled-in module … [See Man Page]'
complete -c tcmodinfo -s t --description 'Specify the Type of module to load.  Default is filter modules.'
complete -c tcmodinfo -s M --description 'Print out the default setting of given paramete… [See Man Page]'
complete -c tcmodinfo -s C --description 'Request to configure the module using given con… [See Man Page]'
complete -c tcmodinfo -s s --description 'Connect to socket socket.'
complete -c tcmodinfo -s d --description 'Specify the verbosiness level to use, like transcode does.'
complete -c tcmodinfo -s p --description 'Print the compiled-in module path and exit.'
complete -c tcmodinfo -s v --description 'Print version information and exit.  EXAMPLES The command.'

