# tcscan
# Autogenerated from man page /usr/share/man/man1/tcscan.1.gz
# using Deroffing man parser
complete -c tcscan -s i --description 'Specify input source.   If ommited, stdin is assumed.'
complete -c tcscan -s d --description 'With this option you can specify a bitmask to e… [See Man Page]'
complete -c tcscan -s v --description 'Print version information and exit.'

