# tee
# Autogenerated from man page /usr/share/man/man1/tee.1p.gz
# using Deroffing man parser
complete -c tee -o 'i.' --description '"tee: cannot access %s\\n", <pathname> Historica… [See Man Page]'

