# tex2lyx
# Autogenerated from man page /usr/share/man/man1/tex2lyx.1.gz
# using Type1
complete -c tex2lyx -s c --description 'Class.'
complete -c tex2lyx -s f --description 'Force.  tex2lyx will not run if the .'
complete -c tex2lyx -s n --description 'Noweb.  Translate a noweb (aka literate programming) file.'
complete -c tex2lyx -s r --description '\\" Regular environments (see the section on Syntax Files).'
complete -c tex2lyx -s s --description 'Syntax files.'
complete -c tex2lyx -o sysdir --description 'Specify a system directory.  Normally, you shouldn\'t need this.'
complete -c tex2lyx -o userdir --description 'Specify a user directory.  Normally, you shouldn\'t need this.'
complete -c tex2lyx -o roundtrip --description 'Call LyX to re-export the created output file to LaTeX.'
complete -c tex2lyx -o help --description 'Help.  Print out usage information and quit.'

