# uic
# Autogenerated from man page /opt/qt/man/man1/uic.1.gz
# using Deroffing man parser
complete -c uic -s o --description 'Write output to file rather than to stdout.'
complete -c uic -o nofwd --description 'Omit forward declarations of custom classes in … [See Man Page]'
complete -c uic -o tr --description 'Use func() instead of tr() for internationalization.'
complete -c uic -o version --description 'Display the version of uic and exit.'

