# uil
# Autogenerated from man page /usr/share/man/man1/uil.1.gz
# using Deroffing man parser
complete -c uil -s I --description 'The compiler should look in the given directory… [See Man Page]'
complete -c uil -s w --description 'Suppress all warnings.'

