# umask
# Autogenerated from man page /usr/share/man/man1/umask.1p.gz
# using Deroffing man parser
complete -c umask -s S --description 'Produce symbolic output.'
complete -c umask -s r -s w -s x --description 'must be preceded by "--" to keep it from being … [See Man Page]'

