# utmpdump
# Autogenerated from man page /usr/share/man/man1/utmpdump.1.gz
# using Deroffing man parser
complete -c utmpdump -s f -l follow --description 'Output appended data as the file grows.'
complete -c utmpdump -s r -l reverse --description 'Undump, write back edited login information int… [See Man Page]'
complete -c utmpdump -s h -l help --description 'Print a help text and exit.'
complete -c utmpdump -s V -l version --description 'Output version information and exit.'

