# uudecode
# Autogenerated from man page /usr/share/man/man1/uudecode.1p.gz
# using Deroffing man parser
complete -c uudecode -s o --description 'A pathname of a file that shall be used instead… [See Man Page]'

