# uuencode
# Autogenerated from man page /usr/share/man/man1/uuencode.1p.gz
# using Deroffing man parser
complete -c uuencode -s m --description 'Encode the output using the MIME Base64 algorit… [See Man Page]'

