# uuidcdef
# Autogenerated from man page /usr/share/man/man1/uuidcdef.1.gz
# using Deroffing man parser
complete -c uuidcdef -s c -l cdef --description 'Print the UUID as an initializer for a C struct… [See Man Page]'
complete -c uuidcdef -s r -l random --description 'Demand that the random-based algorithm be used … [See Man Page]'
complete -c uuidcdef -s t -l time --description 'Demand that the time-based algorithm be used to… [See Man Page]'
complete -c uuidcdef -s u -l uuid --description 'Print the UUID like: "26175a27-c35d-4615-8dfb-1509eab28ef8".'

