# vi
# Autogenerated from man page /usr/share/man/man1/vi.1p.gz
# using Deroffing man parser
complete -c vi -s c --description 'See the ex command description of the -c option.'
complete -c vi -s r --description 'See the ex command description of the -r option.'
complete -c vi -s R --description 'See the ex command description of the -R option.'
complete -c vi -s t --description 'See the ex command description of the -t option.'
complete -c vi -s w --description 'See the ex command description of the -w option.'
complete -c vi -s 1 --description 'uppercase counterparts shall be changed to uppe… [See Man Page]'
complete -c vi -o '1).' --description '.'
complete -c vi -o '1)).' --description '.'
complete -c vi -o '1)' --description '<control>-U.'

