# wall
# Autogenerated from man page /usr/share/man/man1/wall.1.gz
# using Deroffing man parser
complete -c wall -s n -l nobanner --description 'Suppress banner.'
complete -c wall -s t -l timeout --description 'Write  timeout to terminals in seconds.'
complete -c wall -s V -l version --description 'Output version and exit.'
complete -c wall -s h -l help --description 'Output help and exit.'

