# wildmidi
# Autogenerated from man page /usr/share/man/man1/wildmidi.1.gz
# using Deroffing man parser
complete -c wildmidi -s b -l reverb --description 'Turns on an 8 point reverb engine that adds dep… [See Man Page]'
complete -c wildmidi -s c -l config_file --description 'Uses the configuration file stated by config-fi… [See Man Page]'
complete -c wildmidi -s d -l auddev --description 'Send the audio to device instead of the default.'
complete -c wildmidi -s e -l enhanced_resample --description 'Switches to a gauss based resampling algorithm … [See Man Page]'
complete -c wildmidi -s h -l help --description 'Displays command line options . PP.'
complete -c wildmidi -s l -l log_vol --description 'Some MIDI files have been recorded on hardware … [See Man Page]'
complete -c wildmidi -s m -l master_volume --description 'Set the overall volume level to volume-level.'
complete -c wildmidi -s o -l wavout --description 'Records the audio in wav format to wav-file. PP.'
complete -c wildmidi -s r -l rate --description 'Set the audio output rate to sndrate.'
complete -c wildmidi -s v -l version --description 'Display version and copyright information.'
complete -c wildmidi -s k -l test_bank --description 'Set the test bank to N.  Range is 0 to 127.'
complete -c wildmidi -s p -l test_patch --description 'Set the test patch to N.  Range is 0 to 127.'
complete -c wildmidi -s t -l test_midi --description 'Plays the built in test midi which plays all 127 notes.'

