# wvWare
# Autogenerated from man page /usr/share/man/man1/wvWare.1.gz
# using Deroffing man parser
complete -c wvWare -s c -l charset --description 'word 97 documents are stored in one of two form… [See Man Page]'
complete -c wvWare -s p -l password --description 'Due to heroic work done by a great team of work… [See Man Page]'
complete -c wvWare -s d -l dir --description 'If dir is used then any created graphics will b… [See Man Page]'
complete -c wvWare -s x -l config --description 'Use this to give the location of the config file.'

