# xfce4-mixer
# Autogenerated from man page /usr/share/man/man1/xfce4-mixer.1.gz
# using Deroffing man parser
complete -c xfce4-mixer -s d -l debug --description 'Print diagnostic output useful for debugging to stderr.'
complete -c xfce4-mixer -s h -s '?' -l help --description 'Print a summary of all command line options and exit.'
complete -c xfce4-mixer -s V -l version --description 'Print the version number and exit.  EXIT STATUS.'

