# xmbind
# Autogenerated from man page /usr/share/man/man1/xmbind.1.gz
# using Deroffing man parser
complete -c xmbind -o display --description 'Specifies the display to use.'
complete -c xmbind -l help --description 'Displays a help summary and then exits.'
complete -c xmbind -l version --description 'Outputs version information about xmbind and then exits.'

