# xneur
# Autogenerated from man page /usr/share/man/man1/xneur.1.gz
# using Deroffing man parser
complete -c xneur -s v -l version --description 'Print program version and exit.'
complete -c xneur -s h -l help --description 'List available options.'
complete -c xneur -s a -l about --description 'About XNeur.'
complete -c xneur -s f -l force --description 'Force run, skip checking for other running instances of XNeur.'
complete -c xneur -s g -l generate --description 'Generate proto and proto3 files from layout and… [See Man Page]'

