# y4mcolorbars
# Autogenerated from man page /usr/share/man/man1/y4mcolorbars.1.gz
# using Type1
complete -c y4mcolorbars -s n --description 'Output a total of \'num\' output frames.  [default: 1].'
complete -c y4mcolorbars -s F --description 'Set framerate encoded in output stream, as an e… [See Man Page]'
complete -c y4mcolorbars -s W --description 'Set frame width.  [default: 720].'
complete -c y4mcolorbars -s H --description 'Set frame height.  [default: 480].'
complete -c y4mcolorbars -s A --description 'Set pixel aspect ratio encoded in output stream… [See Man Page]'
complete -c y4mcolorbars -s I --description 'Set interlacing mode, used to interpret the PPM… [See Man Page]'
complete -c y4mcolorbars -s Q --description 'Data to place in the "-I/+Q" patches in the bot… [See Man Page]'
complete -c y4mcolorbars -s S --description 'Set chroma subsampling mode.'

