# y4mtopnm
# Autogenerated from man page /usr/share/man/man1/y4mtopnm.1.gz
# using Type1
complete -c y4mtopnm -s P --description 'Produce PAM format output, instead of PPM and/or PGM.'
complete -c y4mtopnm -s D --description 'Produce a separate output image for each field of each frame.'
complete -c y4mtopnm -s f --description 'Produce a special \'flattened\' output, most usef… [See Man Page]'

