# y4munsharp
# Autogenerated from man page /usr/share/man/man1/y4munsharp.1.gz
# using Type1
complete -c y4munsharp -s v --description 'Set verbosity level (0 = quiet, 1 = normal, 2 =… [See Man Page]'
complete -c y4munsharp -s h --description 'Print a suage summary and exit.'
complete -c y4munsharp -s L --description 'Y\' (luma) unsharp parameters.'

