# yacc
# Autogenerated from man page /usr/share/man/man1/yacc.1p.gz
# using Deroffing man parser
complete -c yacc -s b --description 'Use file_prefix instead of y as the prefix for … [See Man Page]'
complete -c yacc -s d --description 'Write the header file; by default only the code… [See Man Page]'
complete -c yacc -s l --description 'Produce a code file that does not contain any #line constructs.'
complete -c yacc -s p --description 'sp Use sym_prefix instead of yy as the prefix f… [See Man Page]'
complete -c yacc -s t --description 'Modify conditional compilation directives to pe… [See Man Page]'
complete -c yacc -s v --description 'Write a file containing a description of the pa… [See Man Page]'

