# yuv2lav
# Autogenerated from man page /usr/share/man/man1/yuv2lav.1.gz
# using Type1
complete -c yuv2lav -s o --description 'This (compulsorary) option sets the name of the… [See Man Page]'
complete -c yuv2lav -s f --description 'This sets the output file format, which has to be one of .'
complete -c yuv2lav -s q --description 'This option specifies the JPEG encoding quality… [See Man Page]'
complete -c yuv2lav -s b --description 'This option specifies the size of the buffer (i… [See Man Page]'
complete -c yuv2lav -s m --description 'This is the maximum size (in MB) per file.'
complete -c yuv2lav -s I --description 'Force a specific interlacing type.'
complete -c yuv2lav -s w --description 'This is the WAV file containing audio data to b… [See Man Page]'
complete -c yuv2lav -s v --description 'Verbosity level.'

