# yuvdenoise
# Autogenerated from man page /usr/share/man/man1/yuvdenoise.1.gz
# using Deroffing man parser
complete -c yuvdenoise -s g --description 'This sets the thresholds for the gaussian filter.'
complete -c yuvdenoise -s m --description 'This sets the thresholds for the pre-processing… [See Man Page]'
complete -c yuvdenoise -s r --description 'This sets the thresholds for adding random "noi… [See Man Page]'
complete -c yuvdenoise -s t --description 'This sets the thresholds for the temporal noise-filter.'
complete -c yuvdenoise -s M --description 'This sets the thresholds for the post-processin… [See Man Page]'

