# yuvfps
# Autogenerated from man page /usr/share/man/man1/yuvfps.1.gz
# using Deroffing man parser
complete -c yuvfps -s r --description 'Specifies the resulting stream frame rate.'
complete -c yuvfps -s s --description 'Ignores the frame rate in the input stream and … [See Man Page]'
complete -c yuvfps -s i --description 'Specifies the interlacing mode of the resulting stream.'
complete -c yuvfps -s I --description 'Ignores the interlacing mode information in the… [See Man Page]'
complete -c yuvfps -s c --description 'Changes the stream header frame rate and interl… [See Man Page]'
complete -c yuvfps -s n --description 'By default yuvfps tries to find a normalized framerate.'
complete -c yuvfps -s w --description 'Produce each output frame/field as a weighted a… [See Man Page]'
complete -c yuvfps -s v --description 'Set verbosity level.   0 = warnings and error messages only.'

