# yuvmedianfilter
# Autogenerated from man page /usr/share/man/man1/yuvmedianfilter.1.gz
# using Type1
complete -c yuvmedianfilter -s r --description 'Radius for luma median (default: 2 pixels).'
complete -c yuvmedianfilter -s R --description 'Radius for chroma median (default: 2 pixels).'
complete -c yuvmedianfilter -s t --description 'Trigger threshold for luma (default: 2 [0=disable]).'
complete -c yuvmedianfilter -s T --description 'Trigger threshold for chroma (default: 2 [0=disable]).'
complete -c yuvmedianfilter -s I --description 'Interlacing type (0=no, 1=yes, default: taken from yuv stream).'
complete -c yuvmedianfilter -s f --description 'Fast mode, i. e.'
complete -c yuvmedianfilter -s w --description 'In fast mode, the weight given to the current v… [See Man Page]'
complete -c yuvmedianfilter -s c --description 'In slow mode, more than this fraction of the pi… [See Man Page]'
complete -c yuvmedianfilter -s s --description 'Number of beginning frames to skip.'
complete -c yuvmedianfilter -s v --description 'Verbosity level (0, 1 or 2).'

