# yuvplay
# Autogenerated from man page /usr/share/man/man1/yuvplay.1.gz
# using Deroffing man parser
complete -c yuvplay -s s --description 'The size of the SDL window.'
complete -c yuvplay -s t --description 'Set the window title.'
complete -c yuvplay -s f --description 'Override the framerate specified in the input stream header.'
complete -c yuvplay -s c --description 'By default, yuvplay will try to play at the fra… [See Man Page]'
complete -c yuvplay -s v --description 'Set the verbosity of user feedback.'

