# ziptorrent
# Autogenerated from man page /usr/share/man/man1/ziptorrent.1.gz
# using Deroffing man parser
complete -c ziptorrent -s h --description 'Display a short help message and exit.'
complete -c ziptorrent -s n --description 'Don\'t actually change archives, just print what would be done.'
complete -c ziptorrent -s V --description 'Display version information and exit.'
complete -c ziptorrent -s v --description 'Be verbose: print which archives are already to… [See Man Page]'

